### ISSUE TITLE
About the sampling strategy of slowfast feature extraction

### ISSUE THREAD

**Issue by NNNNAI** [facebookresearch/Ego4d#100]
Thanks for sharing your work.
You guys provided a slowfast feature for each video. I just wondering how did you sample the frames in the raw videos as the input of slowfast model. Casuse I am doing some experiment but I need the exact index of the corresponding slowfast input frames.It would be great if you could provide a function for sampling. 
Thanks for your time, have a nice day~.

**Comment by miguelmartin75** [comment]
The documentation explains this. See here: https://ego4d-data.org/docs/data/features/#description

SlowFast has a stride of 16 frames and a window size of 32. If a video has 100 frames, we start with frames [0, 31] feed it in the model and obtain the features, then move to frames [16, 47] then move to frames [32, 63], etc. etc. You can see the corresponding code [here](https://github.com/facebookresearch/Ego4d/blob/main/ego4d/features/dataset.py#L81). There is potentially one additional feature for the end of the video - this is described in the [example](https://ego4d-data.org/docs/data/features/#example-window-stride).

Also please note that omnivore features are released and available. These have a stride of 6 frames and window size of 32, which equates to 5 frames per second. They should be higher quality features than slowfast.
