### ISSUE TITLE
Error with CLI Download

### ISSUE THREAD

**Issue by abcdvzz** [facebookresearch/Ego4d#101]
When I run the command: `python-m ego.cli.cli .....`, the error `Error when finding module specification for ego.cli.cli, ModuleNotFoundError: No Module named 'ego4d` occurs. Could you please tell me how I can fix this?

**Comment by miguelmartin75** [comment]
You should install ego4d pip package, i.e. run `pip install .` (in the repository) prior to running the CLI.

**Comment by yee-ran** [comment]
@miguelmartin75 hey, could you specify how to install ego4d? I keep getting this error:

ERROR: Could not find a version that satisfies the requirement ego4d (from versions: none)
ERROR: No matching distribution found for ego4d

Thank you so much!!!

**Comment by miguelmartin75** [comment]
We haven't setup the pip package on PyPI yet. You'll have to clone the repository and perform `pip install .`, i.e. like so:

```bash
git clone github.com/facebookresearch/Ego4d.git
cd Ego4d
pip install .
```

If you use pyenv or conda, you should set up your python environment before the pip install, e.g.

For conda:
```
conda create --name ego4d
conda activate ego4d
pip install .
```

For pyenv
```
mkdir my_ego4d_project && cd my_ego4d_project
python3 -m venv create env
source env/bin/activate
cd /location/where/ego4d_is/Ego4d
pip install .
```

**Comment by yee-ran** [comment]
Thank you so much!! It works!

**Comment by antoninofurnari** [comment]
Hi All, a quick hack to install the package without cloning: 

```
conda create -n ego4d python=3.8
conda activate ego4d
pip install https://github.com/facebookresearch/Ego4d/archive/main.zip
```
