### ISSUE TITLE
Total number of videos

### ISSUE THREAD

**Issue by xvjiarui** [facebookresearch/Ego4d#104]
Hi Ego4d Team,

Thanks for the great work!

May I ask how many videos I should expect when downloading with `full_scale`, i.e. running `python -m ego4d.cli.cli --output_directory="~/ego4d_data" --datasets full_scale annotations --metadata --aws_profile_name ego4d`? 

I am downloading 9674 videos, is that correct?

How about `clips` dataset option?

**Comment by astephens43** [comment]
in addition, I downloaded full_scale filtered by --Brighton and received only 360 videos when i expected 770 (from the Metadata) - is there an obvious reason why?

**Comment by ebyrne** [comment]
9674 is correct for videos, apologies on the delay.

--Brighton is not a valid option.  Please see the CLI options here: https://github.com/facebookresearch/Ego4d/blob/main/ego4d/cli/README.md

**Comment by YouJiacheng** [comment]
@ebyrne 
Sorry to bother you in a closed issue. There are only 9645 videos in metadata(ego4d.json) now. Did the dataset update?
