### ISSUE TITLE
Difference between documentation and code

### ISSUE THREAD

**Issue by xvjiarui** [facebookresearch/Ego4d#105]
Hi Ego4d Team,

Thanks for your great work.

In the `cli/README.md`, it states the dataset options are `[annotations, full_scale, clips]`. But in the documentation here https://ego4d-data.org/docs/data/videos/ , it states there are 3 types of videos, `Canonical videos`, `Canonical Clips`, and `Video Components`. 

May I ask how they correspond to each other and how to download them?

**Comment by miguelmartin75** [comment]
Thanks for the feedback on the docs. It does seem not very clear. We will iterate on them.

- Canonical videos are `full_scale`
- Canonical clips are `clips`
-  `annotations` are annotations over the videos. Please see this page for their schemas: https://ego4d-data.org/docs/data/annotations/, this page for the higher level overview: https://ego4d-data.org/docs/benchmarks/overview/ and this page for how the annotation process was performed: https://ego4d-data.org/docs/data/annotation-guidelines/ 
 
Finally, for video components. Please refer to the docs here:  https://ego4d-data.org/docs/data/unprocessed_data/
