### ISSUE TITLE
"parent_start_sec" for social benchmark

### ISSUE THREAD

**Issue by ziweizhao1993** [facebookresearch/Ego4d#112]
Hi,

I am working on the social benchmark. The download scripts requires "parent_start_sec" and "parent_end_sec", but they are not in the annotation files (av_val.json and av_train.json).
I wonder if it should be "video_start_sec" and "video_end_sec" now? Those are the closest I can find in the annotation.

Thank you.

**Comment by ebyrne** [comment]
For the social benchmark I believe that's no longer the case.   Can you advise where you currently see that and reopen the issue if so? 

And apoloiges on the long response time!
