### ISSUE TITLE
narrations.json in structured format

### ISSUE THREAD

**Issue by astephens43** [facebookresearch/Ego4d#114]
if anyone has managed to get the narrations.json data into a structured format, please share how.  Parsing from JSON is proving challenging
A

**Comment by miguelmartin75** [comment]
What have you tried here? Parsing the narration file should be relatively simple. Here is an example to get all narrations: https://github.com/facebookresearch/Ego4d/blob/vaclip/ego4d/vaclip/preprocess.py#L46
