### ISSUE TITLE
Is there any existing hand-object interaction prediction work that consumes Ego4d?

### ISSUE THREAD

**Issue by jmgrn61** [facebookresearch/Ego4d#119]
Hi,

Can you point me some existing models that can perform successful hand-object interaction on Ego4d data?  Either small examples from FAIR or some other papers will be OK.

Thanks

**Comment by devanshk** [comment]
Hey @jmgrn61!

Thanks for the question! See our benchmark repositories for working examples, in particular these two:
Hand and Object Interaction: https://github.com/EGO4D/hands-and-objects
Forecasting Future Interaction: https://github.com/EGO4D/forecasting

All benchmark repos are findable in our docs: https://ego4d-data.org/docs/benchmarks/overview/.

Please let us know if you have any issues running these!
