### ISSUE TITLE
About the annotations

### ISSUE THREAD

**Issue by jasonseu** [facebookresearch/Ego4d#121]
Hi, thanks for your awesome work. Is the annotations downloaded by `ego4d --output_directory="~/ego4d_data" --datasets clips annotations` and `ego4d --output_directory="~/ego4d_data" --datasets full_scale annotations` the same?

**Comment by devanshk** [comment]
Hey @jasonseu, thanks for the question!

The `--datasets` arg lets you pick which datasets to download. In the first command you're downloading the 'clips' and 'annotations' datasets, and in the second you're downloading the 'full_scale' and 'annotations' datasets.

So the annotations downloaded by both are the same, and you can see how the schema supports both videos and clips in the [docs schema](https://ego4d-data.org/docs/data/annotations-schemas/)!
