### ISSUE TITLE
Video 011ee98a-afc2-4088-b4d1-e0f7d84f3611 is abnormal

### ISSUE THREAD

**Issue by YouJiacheng** [facebookresearch/Ego4d#128]
From timstamp 532s to 1063s.
Video player(including https://visualize.ego4d-data.org/011ee98a-afc2-4088-b4d1-e0f7d84f3611 web player) and nvidia-dali will stuck.
PyAV will decode black frames.

**Comment by miguelmartin75** [comment]
This video is partially redacted. You can read this from the top-level metadata file: `https://ego4d-data.org/docs/data/metadata/`. Use the `redacted_intervals` property.

The way the video player does handle it is a bit strange, it should just be a blank video section. 

As a side note. If you get DALI working with seeking, please let me know. Last time I tried this library it did not work for me, but this was a while ago.

**Comment by YouJiacheng** [comment]
Thanks! But it seems that video redacted from the beginning can be correctly played or processed by DALI?
Do Ego4D team plan to provide a version that substitute redacted blank intervals with black frames?
I can't get DALI working with blank video sections...(It seems that DALI doesn't have seeking functionality.)
PyAV is 5x slower than DALI.

**Comment by miguelmartin75** [comment]
Apologies for the delayed response.

>Do Ego4D team plan to provide a version that redacted blank intervals are substituted with black frames?

Blank intervals are padded with black frames. Specifically the way the canonical videos are constructed are:
1. Each video component normalized to 30fps, VP9 with other options (normalizing SAR and etc.)
2. Blank sections constructed with an ffmpeg command, using black pixels as values, specifically this command is used `ffmpeg -t <duration> -s <w>x<h> -f rawvideo -pix_fmt rgb24 -r <fps> -i /dev/zero <path>.mpeg`
3. Components from 2 are compressed with the same code as (1)
4. ffmpeg's concat routine is used to combine the videos to form the canonical video

I will have a look at DALI for redacted and non-redacted videos.

**Comment by SJTUwxz** [comment]
Closing this issue for now. Please feel free to re-open it if you have further questions.
