### ISSUE TITLE
What does status in narrations.json mean?

### ISSUE THREAD

**Issue by YouJiacheng** [facebookresearch/Ego4d#129]
There are 3 status, "redacted", "redacted_partial" and "complete"
There are 466 videos narrations status="complete" but metadata has_redacted_regions=True
There are 651 videos narrations status="redacted" but metadata has_redacted_regions=False

**Comment by ebyrne** [comment]
Status represents whether narrations were redacted (i.e. removed - either fully or partially) for those videos since those intervals are in the test sets.  We'll update the annotation schemas in the docs to represent this.

**Comment by YouJiacheng** [comment]
Thanks for reply! So IIUC, narration redaction is irrelevant to video redaction?
