### ISSUE TITLE
Bugs when decode video via pyav 

### ISSUE THREAD

**Issue by starsholic** [facebookresearch/Ego4d#131]
Hi,
    Some videos encountered strange bugs like below
    `video = av.open(path)`
    `video.seek(0) # PermissionError: [Errno 1] Operation not permitted`
   I've checked out the buggy video and everything seems normal. 

  So, could I remove the Line65 `self.vid._container.seek(0)` in the features/dataset.py ?

**Comment by starsholic** [comment]
Besides, what shouldI do if it raises `AssertionError: failed assumption pts in order` in features/dataset.py when decode video?

**Comment by miguelmartin75** [comment]
Which video is this for?

**Comment by starsholic** [comment]
Thanks for ur reply! 
I use this code to extract video feature of the other dataset, the buggy video is [here](https://drive.google.com/file/d/1zSum-D_Oy0H6uFMHPixvDs2Wzs7Hv4kj/view?usp=sharing). 
Could you download it and have a try? Thanks!
<img width="547" alt="截屏2022-08-15 18 43 51" src="https://user-images.githubusercontent.com/52476332/184621867-42a0648a-7e89-4722-bd68-a442d420eedd.png">

**Comment by miguelmartin75** [comment]
This video is not an ego4d video. Did you have an ego4d video to show as an example? Otherwise I think you should report this to PyAV's github issues: https://github.com/PyAV-Org/PyAV

**Comment by starsholic** [comment]
okay, I have reported this to pyav repo here: https://github.com/PyAV-Org/PyAV/issues/1027
