### ISSUE TITLE
Can the download be resumed after an interruption?

### ISSUE THREAD

**Issue by Fanye12** [facebookresearch/Ego4d#147]

**Comment by devanshk** [comment]
Hey @Fanye12, thanks for your question! Yes, we recently added incremental download-resumes to the CLI.

Please make sure you have the current version of the CLI by running ```pip install --upgrade ego4d```, then retry your download. If you still have issues, try the ```--bypass-existing``` and ```--skip-s3-checks``` flags described by running ```ego4d -h```. **--bypass-existing is a temporary fix** - it will ignore video version checks so please only use this to complete the download once.

Let us know if you still have problems!
