### ISSUE TITLE
Cannot submit information

### ISSUE THREAD

**Issue by Weijian-li** [facebookresearch/Ego4d#149]
Cannot submit information at https://ego4ddataset.com/. Error message is 'Failed to Fetch'. Do you know how to solve this? Thanks!

**Comment by ebyrne** [comment]
We can confirm there's a server error and will be resolved shortly.  Apologies on the delay here.

**Comment by Weijian-li** [comment]
Thanks!

**Comment by s-yamazaki31** [comment]
I'm facing the same issue that I cannot submit information at https://ego4ddataset.com/. The error message is 'Failed to Fetch'.
Could you help me to solve this?
