### ISSUE TITLE
"Fail to fetch" when applying for license

### ISSUE THREAD

**Issue by fylwen** [facebookresearch/Ego4d#150]
Hello.

When I applied for the license via https://ego4ddataset.com/ as instructed in https://ego4d-data.org/docs/start-here/#license-agreement, it showed "fail to fetch" after I submit my personal info, and I did not receive any email regarding the AWS. Therefore I write to seek your help.

Thanks a lot!

Best regards,
Frances

**Comment by ebyrne** [comment]
This was a webserver error and has since been resolved.  We apologize for the inconvenience, please try again!

**Comment by iranroman** [comment]
Hello, I still have this issue. Can someone please help me?

**Comment by chaitanya100100** [comment]
@iranroman did you resolve this? I am also facing similar error while renewing the license.
