### ISSUE TITLE
SSLError occured when downloading dataset

### ISSUE THREAD

**Issue by wengup** [facebookresearch/Ego4d#151]
Hello,

 'SSLError'  ocurred when I ran the command 'ego4d --output_directory="G:/Folder2/ego4d_data" --datasets clips' to download  clips. 

Could you tell me how to solve it?  Thanks in advance!

![image](https://user-images.githubusercontent.com/68762120/194451011-5e226a14-6d47-4095-9cd0-ac3e0cc93b10.png)

**Comment by dreamerlin** [comment]
Same Error, how did you solve it?

**Comment by Mr-Bigworth** [comment]
Same Error...

**Comment by wengup** [comment]
i downloaded it from China with vpn, which led to the SSL error. Therefore, i closed vpn and solved it. 

@dreamerlin @Mr-Bigworth

**Comment by Mr-Bigworth** [comment]
> i downloaded it from China with vpn, which led to the SSL error. Therefore, i closed vpn and solved it.
> 
> @dreamerlin @Mr-Bigworth

I also download it from China, but whether I use VPN or not, this error still exists. :-(

**Comment by cyfedu1024** [comment]
Maybe we need to close the firewall, we can use this commanc to close the firewall: systemctl stop ufw, then we can check the whether the ufw is open : systemctl status ufw. Above operation is useful for me.

**Comment by gahgdug** [comment]
Hello, this error has been solved, but when downloading in China, the connection will time out, how do you solve it? thank you！！！
this is the problem“EndpointConnectionError: Could not connect to the endpoint URL: "https://ego4d-unict.s3.eu-central-1.amazonaws.com/public/v2/clips/0028cd34-25b8-4375-85b5-37f356d4c308.mp4"，“ARNING:urllib3.connectionpool:Connection pool is full, discarding connection: ego4d-unict.s3.eu-central-1.amazonaws.com. Connection pool size: 10”，“File "/home/hu/anaconda3/envs/ego4d/lib/python3.9/site-packages/urllib3/connection.py", line 186, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <botocore.awsrequest.AWSHTTPSConnection object at 0x7fac5c301b80>: Failed to establish a new connection: [Errno 101] Network is unreachable”

**Comment by gahgdug** [comment]
> Same Error...

Are you successful download ego4d?

**Comment by wengup** [comment]
This error may occur when the downloading files are too large (>10GB). I filtered the videos to get a split file (.txt) from this [link](https://visualize.ego4d-data.org/) and wrote a script to download the videos one by one. Hope this helps! 
Another possible reason is that the AWS CLI region should be set to American, and try one more times.
Alternatively, you could also check out [forums](https://discuss.ego4d-data.org/latest) for more info or contact the official support.

> Hello, this error has been solved, but when downloading in China, the connection will time out, how do you solve it? thank you！！！ this is the problem“EndpointConnectionError: Could not connect to the endpoint URL: "[https://ego4d-unict.s3.eu-central-1.amazonaws.com/public/v2/clips/0028cd34-25b8-4375-85b5-37f356d4c308.mp4"，“ARNING:urllib3.connectionpool:Connection](https://ego4d-unict.s3.eu-central-1.amazonaws.com/public/v2/clips/0028cd34-25b8-4375-85b5-37f356d4c308.mp4%22%EF%BC%8C%E2%80%9CARNING:urllib3.connectionpool:Connection) pool is full, discarding connection: ego4d-unict.s3.eu-central-1.amazonaws.com. Connection pool size: 10”，“File "/home/hu/anaconda3/envs/ego4d/lib/python3.9/site-packages/urllib3/connection.py", line 186, in _new_conn raise NewConnectionError( urllib3.exceptions.NewConnectionError: <botocore.awsrequest.AWSHTTPSConnection object at 0x7fac5c301b80>: Failed to establish a new connection: [Errno 101] Network is unreachable”

**Comment by gahgdug** [comment]
> This error may occur when the downloading files are too large (>10GB). I filtered the videos to get a split file (.txt) from this [link](https://visualize.ego4d-data.org/) and wrote a script to download the videos one by one

thank you very much

**Comment by Aopolin-Lv** [comment]
> This error may occur when the downloading files are too large (>10GB). I filtered the videos to get a split file (.txt) from this [link](https://visualize.ego4d-data.org/) and wrote a script to download the videos one by one. Hope this helps! Another possible reason is that the AWS CLI region should be set to American, and try one more times. Alternatively, you could also check out [forums](https://discuss.ego4d-data.org/latest) for more info or contact the official support.
> 
> > Hello, this error has been solved, but when downloading in China, the connection will time out, how do you solve it? thank you！！！ this is the problem“EndpointConnectionError: Could not connect to the endpoint URL: "[https://ego4d-unict.s3.eu-central-1.amazonaws.com/public/v2/clips/0028cd34-25b8-4375-85b5-37f356d4c308.mp4"，“ARNING:urllib3.connectionpool:Connection](https://ego4d-unict.s3.eu-central-1.amazonaws.com/public/v2/clips/0028cd34-25b8-4375-85b5-37f356d4c308.mp4%22%EF%BC%8C%E2%80%9CARNING:urllib3.connectionpool:Connection) pool is full, discarding connection: ego4d-unict.s3.eu-central-1.amazonaws.com. Connection pool size: 10”，“File "/home/hu/anaconda3/envs/ego4d/lib/python3.9/site-packages/urllib3/connection.py", line 186, in _new_conn raise NewConnectionError( urllib3.exceptions.NewConnectionError: <botocore.awsrequest.AWSHTTPSConnection object at 0x7fac5c301b80>: Failed to establish a new connection: [Errno 101] Network is unreachable”

Could you provide more details about hwo to download the videos one by one! Much thanks.

**Comment by Aopolin-Lv** [comment]
> > > This error may occur when the downloading files are too large (>10GB). I filtered the videos to get a split file (.txt) from this [link](https://visualize.ego4d-data.org/) and wrote a script to download the videos one by one. Hope this helps! Another possible reason is that the AWS CLI region should be set to American, and try one more times. Alternatively, you could also check out [forums](https://discuss.ego4d-data.org/latest) for more info or contact the official support.
> > > > Hello, this error has been solved, but when downloading in China, the connection will time out, how do you solve it? thank you！！！ this is the problem“EndpointConnectionError: Could not connect to the endpoint URL: "[https://ego4d-unict.s3.eu-central-1.amazonaws.com/public/v2/clips/0028cd34-25b8-4375-85b5-37f356d4c308.mp4"，“ARNING:urllib3.connectionpool:Connection](https://ego4d-unict.s3.eu-central-1.amazonaws.com/public/v2/clips/0028cd34-25b8-4375-85b5-37f356d4c308.mp4%22%EF%BC%8C%E2%80%9CARNING:urllib3.connectionpool:Connection) pool is full, discarding connection: ego4d-unict.s3.eu-central-1.amazonaws.com. Connection pool size: 10”，“File "/home/hu/anaconda3/envs/ego4d/lib/python3.9/site-packages/urllib3/connection.py", line 186, in _new_conn raise NewConnectionError( urllib3.exceptions.NewConnectionError: <botocore.awsrequest.AWSHTTPSConnection object at 0x7fac5c301b80>: Failed to establish a new connection: [Errno 101] Network is unreachable”
> > 
> > 
> > Could you provide more details about hwo to download the videos one by one! Much thanks.
> 
> For example, to download NLQ videos, filter the videos by selecting “NLQ” in the search box on this [site](https://visualize.ego4d-data.org/?q=%22benchmarks+include+nlq%22). Then, click the button in the upper right corner to download a txt file containing the uids of the NLQ videos. Finally, use the official [CLI tool](https://ego4d-data.org/docs/CLI/) to download the videos using the txt file.

Thank your for the detailed descriptions.
