### ISSUE TITLE
What's the end timestamp of each narration?

### ISSUE THREAD

**Issue by zhengsipeng** [facebookresearch/Ego4d#152]
Hi, thanks for your great work!
I notice that the i-th narration for a video in "narration.json" is labeled like :
{timestamp_sec: 19.2, timestamp_frame: 1823, narration_text: "hello"}

I understand 'timestamp_sec' is the start timestamp of i-th narration, but what is its end timestamp? the i+1-th narration's timestamp_sec?
But I notice it's quite often that i+1-th timestamp_sec < i-th timestamp_sec, does it mean the annotation fault?

**Comment by ebyrne** [comment]
The narrations are point in time annotations, meaning it's just a single timestamp per narrations.  Please see further details here: https://ego4d-data.org/docs/data/annotation-guidelines/#narrations
