### ISSUE TITLE
Getting action labels for point of no return annotations

### ISSUE THREAD

**Issue by dmoltisanti** [facebookresearch/Ego4d#157]
Hi there, thanks a lot for your work!

I would like to get the action labels matching the point of no return annotations. That is, given an annotation from `fho_oscc-pnr_train.json`, I would like to get the corresponding action segment, in order to get the verb and noun labels corresponding to the OSCC annotation.

Quoting from the [Hand & Object Interactions docs](https://ego4d-data.org/docs/benchmarks/hands-and-objects/#annotations)

> We select the data to annotate based on activities that are likely to involve hand-object interactions (e.g., knitting, carpentry, baking, etc.). We start by labeling each narrated hand-object interaction. For each, we label three moments in time (pre, PNR, post) and the bounding boxes for the hands, tools, and objects in each of the three frames. **We also annotate the state change types (remove, burn, etc.), action verbs, and nouns for the objects.**

it seems that indeed it should be possible to get verbs and nouns (the action labels I'm after) for each PNR annotation. However, I could not find this information. 

In `fho_scod_train.json` I found object labels corresponding to each PNR, however I could not find the verb label.

I tried matching the PNR in `fho_oscc-pnr_train.json`  to the action segments in `fho_lta_train.json`, however I wonder if there is a better way of achieving this goal.

Thanks in advance!

**Comment by ebyrne** [comment]
As you've noted there's not a great way to do that currently.  The good news is that we're about to release a new set of FHO annotations and an fho_master.json that will correlate those annotations.  Release should be coming next week and I'll follow up here as well.

Apologies on the delay!

**Comment by dmoltisanti** [comment]
That's good news, looking forward to the new annotations!

Thanks

**Comment by SJTUwxz** [comment]
Closing this issue for now. Please feel free to re-open it if the problem persists.
