### ISSUE TITLE
How to get the training dataset for Hands & Objects Benchmark

### ISSUE THREAD

**Issue by Mr-Bigworth** [facebookresearch/Ego4d#159]
If I only want to get the training dataset for Hands & Objects Benchmark, which dataset should l choose, annotations or clips?
ego4d --output_directory="~/ego4d_data" --datasets annotations --metadata
or
ego4d --output_directory="~/ego4d_data" --datasets clips --metadata

**Comment by ebyrne** [comment]
annotations are the json files with the annotations themselves.  Clips are the video segments that correspond to specific annotations (typically).  If you're downloading clips for a specific benchmark, you'll want to filter by the benchmark as well.  (Currently, you can only filter on FHO for clips, but we're updating that shortly with the next release to support the sub-benchmarks if you want only hands.)  Please see the CLI docs for more info: https://ego4d-data.org/docs/CLI/
