### ISSUE TITLE
Failed To Fetch

### ISSUE THREAD

**Issue by Davidyao99** [facebookresearch/Ego4d#161]
I am trying to access the Ego4D dataset but the website ([https://ego4ddataset.com/](https://ego4ddataset.com/)) is throwing a Failed To Fetch error. Any idea how I can resolve this? Thank you!

**Comment by ebyrne** [comment]
We can confirm this was a website issue.  Please try again now and it should proceed.  Apologies for the delay and thanks for flagging!

**Comment by relh** [comment]
This issue has re-emerged. I went to go re-fill out a license agreement to re-do HelloSign to re-be-able to get access credentials to re-download the v2 and ran into this issue.

**Comment by relh** [comment]
FYI, although I saw this issue of "failure to fetch" on the website, I DID recieve the email with the access key id and credentials! So check your email and try again even if you see this page.

**Comment by fgy624** [comment]
Hi, when did u  recieve  your accsess key id?

**Comment by fgy624** [comment]
Hi, how long did u recieve your accsess key id?

**Comment by miccooper9** [comment]
Hi i am facing a "Failed to fetch" error when i try to submit my information as an individual on https://ego4ddataset.com/

**Comment by JingzheShi** [comment]
Hi, I'm also facing the exact same issue when trying to submit information as individual on https://ego4ddataset.com/egoexo-license/

**Comment by chaitanya100100** [comment]
@ebyrne It looks like this issue has emerged again. I have been trying to renew my EgoExo4D license and unable to do so.

**Comment by jianwang-mpi** [comment]
I am also having the issue when I update my ego-exo-4d dataset:

![image](https://github.com/facebookresearch/Ego4d/assets/13883222/4a8eed1d-f94d-4631-b08f-4e1312722c7b)

**Comment by bicheng-xu** [comment]
"Failed to fetch" when I am submitting the license for both Ego4D and EgoExo4D as an individual :(
https://ego4ddataset.com/ego4d-license/
https://ego4ddataset.com/egoexo-license/

**Comment by lixinghe1999** [comment]
> "Failed to fetch" when I am submitting the license for both Ego4D and EgoExo4D as an individual :( https://ego4ddataset.com/ego4d-license/ https://ego4ddataset.com/egoexo-license/

Same here, but worked one week before, will try it several days later

**Comment by harry-kim-droid** [comment]
"Failed to fetch" when I am submitting the license for Ego4D

**Comment by patrick-tssn** [comment]
Same question here, I believe something went wrong on the server. @ebyrne Could you please check again?

**Comment by Liux1n** [comment]
Same here, "Failed to fetch" when submitting the license.

**Comment by DecaYale** [comment]
Same here. "Failed to fetch" with chrome.

**Comment by ojh6404** [comment]
Same here, "Failed to fetch" when submitting the license.

**Comment by mumbert4** [comment]
Same here. "Failed to fetch" with chrome.

**Comment by YijunHu2** [comment]
> I am also having the issue when I update my ego-exo-4d dataset:
> 
> ![image](https://private-user-images.githubusercontent.com/13883222/322482235-4a8eed1d-f94d-4631-b08f-4e1312722c7b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzExNjI3MTgsIm5iZiI6MTczMTE2MjQxOCwicGF0aCI6Ii8xMzg4MzIyMi8zMjI0ODIyMzUtNGE4ZWVkMWQtZjk0ZC00NjMxLWIwOGYtNGUxMzEyNzIyYzdiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTA5VDE0MjY1OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJjNjVhMmNiOGYyZTU0N2Y4Yzg3MGE2MDcxZmQ2MTAyNDJhMjk0ZGRhYzMyYWE0NDJhZDc3NTBlN2YyNmIyOGYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.WWpd3W2pAeppPZTFEyESSxkcj5nkApd81i5-krjouH4)

hello there, did you solve this problem? i'm trapped in the same situation.

**Comment by daeunni** [comment]
Same here

**Comment by ajaystar8** [comment]
Same here, "Failed to fetch" when submitting the license.

**Comment by LYX0501** [comment]
Same here, "Failed to fetch" when submitting the license.

**Comment by wine-plum** [comment]
Same here, "Failed to fetch" when submitting the license.

**Comment by YizhuoPip** [comment]
Same here, "Failed to fetch" when submitting the license.

**Comment by Ironieser** [comment]
Same here, "Failed to fetch" when submitting the license.

**Comment by suyogduttjain** [comment]
Hi everyone,

We have been working on rolling out a new license server for Ego4D & EgoExo4D.

We are slowly testing it with a small set of users.

Please use the following links to send a license request:

https://ego4d.dev/request/ego4d
https://ego4d.dev/request/ego-exo4d

Hopefully we will be able to unblock you all very soon!

Suyog
