### ISSUE TITLE
SCOD benchmark

### ISSUE THREAD

**Issue by Davidyao99** [facebookresearch/Ego4d#164]
Is it possible for me to download only the pre, pnr and posts frames used for validation for the SCOD challenge? Downloading the entire video takes up a lot of time and space. Thank you!

**Comment by miguelmartin75** [comment]
This is currently not possible. You can instead download the canonical clips for FHO. These clips are trimmed regions relevant to FHO. You can read documentation about them here: https://ego4d-data.org/docs/data/videos/#canonical-clips - there is a section specific to FHO
