### ISSUE TITLE
Possible errors in Ego4d visualizations

### ISSUE THREAD

**Issue by Davidyao99** [facebookresearch/Ego4d#166]
I am extracting the frames (PNR, pre, and post) for the State change object detection validation set. I noticed that in the Ego4d visualizer, some videos begin at frame 0 and some begin at frame 1. May I confirm that for the frame number in the annotations, they all assume that videos start from frame 0? For example, the pnr frame at frame 5 is essentially the 6th frame of the video? I believe that the videos in the visualizations that start with frame 1 has a off by one frame error in the visualization. The bounding box seems to be tighter if applied to the next frame. Thanks for your time and just wanted to confirm if this is really the case!!

**Comment by miguelmartin75** [comment]
This frame alignment is a known issue - this will be resolved shortly. The reason is due to the start time of the video. If you could send your example along to confirm this that would be great.
