### ISSUE TITLE
Crash on Ego4D Visualizer

### ISSUE THREAD

**Issue by fylwen** [facebookresearch/Ego4d#167]
Greetings. when I try to log in to the Ego4D Visualizer (https://visualize.ego4d-data.org/login) by entering the _Access Key_ from the email entitled _Ego4D Data Access Granted_, I then get a crash by immediately being forced to return to the login page.  And I wonder whether you can help with it.

Thanks a lot.

Regards,
Frances

**Comment by devanshk** [comment]
Hi Frances,

Are you sure you're using your Access ID and not your Access Key? The correct one should start with an 'A'.

As this deals with sensitive secrets, please email us at `info@ego4d-data.org` if that doesn't resolve the issue, so we can discuss this more.

Thanks,
Devansh
