### ISSUE TITLE
Unable to fill the form for dataset access

### ISSUE THREAD

**Issue by Anirudh257** [facebookresearch/Ego4d#178]
I am trying to access the data via the [https://ego4ddataset.com/](https://ego4ddataset.com/) and have filled out the form as an Individual. When I fill in my details, I get this error:
![dataset_access_issue](https://user-images.githubusercontent.com/16001446/224554529-506ea59a-e2cb-47c2-a5c0-0fdcb1285995.png)

My address is greater than 75 characters and I am unable to find a shorter version of it. What can I do?

Reposting from https://discuss.ego4d-data.org/t/unable-to-fill-the-form-for-dataset-access/214

**Comment by ebyrne** [comment]
Please truncate it to 75 characters.  Include the most important info and drop the rest. 

Apologies for the inconvenience!

**Comment by Anirudh257** [comment]
Sure @ebyrne I have resubmitted the form. Hope that it gets accepted now!
