### ISSUE TITLE
MMPose/MMDetection Version Lock and Update Recommendation

### ISSUE THREAD

**Issue by Tau-J** [facebookresearch/Ego4d#196]
Dear Ego4d developers,

I am a contributor to the MMPose project. Firstly, I want to express my gratitude for your use of MMPose in your ego4d repository. It's great to see the project being utilized in various applications.

However, I recently noticed that in your `requirements.txt` file, there is no specific version lock for MMPose. This lack of version specification will lead to compatibility issues for users. The reason is that, last week, MMPose and MMDetection underwent a branch switch. The default branch now uses the new architecture, which is **NOT** backward compatible with the previous versions.

Based on your current implementation, it appears that you are using a version corresponding to the `0.x` branch, specifically `v0.29.0`. To prevent potential issues for your users, I suggest that you update your `requirements.txt` file to lock the MMPose version to v0.29.0, MMDet version to v2.28.2. 

Furthermore, I would like to take this opportunity to invite you to explore the new 1.0 architecture of MMPose. We have made significant improvements in terms of performance and features, which could greatly benefit your project.

Please feel free to reach out if you have any questions or need assistance with the transition to the new version. We're always here to help.

Once again, thank you for using MMPose, and we look forward to seeing the continuous growth of your project.

Best regards,
Tau

**Comment by miguelmartin75** [comment]
Thanks for the PR and information @Tau-J 

I'll merge in your changes.

However, we are planning to use a fork of mmpose / mmdet for the future, which @rawalkhirodkar (https://github.com/rawalkhirodkar) has created. I'm not sure which version the fork is based on or what the fork contains.
