### ISSUE TITLE
Camera intrinsics

### ISSUE THREAD

**Issue by cameronosmith** [facebookresearch/Ego4d#198]
Hi, thanks for collecting this awesome dataset!
I need the camera intrinsics for a computer vision application. Is this a feasible request? Are all the cameras the same across the dataset? If so, I read that you computed the camera parameters using structure from motion for the 3D room scans; could you please provide the cameras and camera calibration from those?
I think there is a notebook [here](https://github.com/facebookresearch/Ego4d/blob/a035fcf16a5b3196f2171b46ec4e5fa348ca30ac/notebooks/COLMAP.ipynb#L13) which computes it, could you also just provide the pose and camera calibration generated by the script if you have that available?

**Comment by SJTUwxz** [comment]
Closing this issue for now. Please feel free to re-open it if the problem persists.
