### ISSUE TITLE
Missing Gaze v1 Data 

### ISSUE THREAD

**Issue by turtleman99** [facebookresearch/Ego4d#200]
I found there are only 31 videos with **gaze** data available for download, aka `v2`. However, the [visualizer](https://visualize.ego4d-data.org/?q=%22modalities+include+gaze%22) indicates that there are `Browsing
2293 / 9645 videos
. Total Duration:
866.21 hours
.` with **gaze** available in `v1`. 

I wonder if these videos can be downloaded or if the visualizer's results are not trustworthy? Any help is appreciated.

Related posts on the Ego4D forum:
1. [Gaze dataset coverage (v1 Vs. v2)](https://discuss.ego4d-data.org/t/gaze-dataset-coverage-v1-vs-v2/292)
2. [Discrepancy between Metadata and Web Visualizer](https://discuss.ego4d-data.org/t/discrepancy-between-metadata-and-web-visualizer/295)

**Comment by miguelmartin75** [comment]
We do not have 2293 videos with Gaze for V1. There is only 31 videos. This is a bug in the visualizer's metadata or the V1 metadata.

cc @devanshk

**Comment by SJTUwxz** [comment]
Closing this issue for now. Please feel free to re-open it if the problem persists.
