### ISSUE TITLE
Error on getting credential on https://ego4ddataset.com/

### ISSUE THREAD

**Issue by nlptrinh** [facebookresearch/Ego4d#213]
I have trouble submitting the information on the website https://ego4ddataset.com/ to get credential for data.

After filling all the information and pressing the "submit" button, there is this error occurred on Safari: "The certificate for this server is invalid. You might be connecting to a server that is pretending to be “internal.ego4ddataset.com” which could put your confidential information at risk." Or this error if I use Chrome: "Failed to fetch".

Could you please fix it? Thank you!

**Comment by devanshk** [comment]
Hey @nlptrinh, thanks for reaching out! It's probably an issue with the license server's certificate renewal. We're looking into it.

**Comment by Todibo99** [comment]
> Hey @nlptrinh, thanks for reaching out! It's probably an issue with the license server's certificate renewal. We're looking into it.

same issue today, please fix.

**Comment by yingsen1** [comment]
encounter same problem

**Comment by chaitanya100100** [comment]
@devanshk , is it still not fixed? I get the same error on chrome 'Failed to fetch' while renewing EgoExo4D license.

**Comment by SJTUwxz** [comment]
Closing this issue for now. Please feel free to re-open it if the problem still persists.
