### ISSUE TITLE
Cannot submit the form for getting a ego4d license on https://ego4ddataset.com/

### ISSUE THREAD

**Issue by Todibo99** [facebookresearch/Ego4d#220]
I am facing the issue "Failed to Fetch" when submitting the form for a license on https://ego4ddataset.com/. It looks like a server problem.

Could any maintainer please have a look at it and fix it?

Thanks!

**Comment by joshmyersdean** [comment]
I am also facing this issue when trying to download. @ebyrne is there any progress on this issue?

**Comment by kxhaaa** [comment]
Same issue, when will it get fixed

**Comment by SJTUwxz** [comment]
Closing this issue for now. Please feel free to re-open it if the problem persists.
