### ISSUE TITLE
Hello,  “EndpointConnectionError” occured when I download this dataset in China！

### ISSUE THREAD

**Issue by gahgdug** [facebookresearch/Ego4d#223]
Hello,

'EndpointConnectionError' ocurred when I ran the command 'eego4d --output_directory="/mnt/4T_disk/Ego4d/yuce" --datasets annotations clips --metadata --benchmarks FHO' .

Could you tell me how to solve it? Thanks in advance!

###  raise EndpointConnectionError(endpoint_url=request.url, error=e)
botocore.exceptions.EndpointConnectionError: Could not connect to the endpoint URL: "https://ego4d-unict.s3.eu-central-1.amazonaws.com/public/v2/clips/0028cd34-25b8-4375-85b5-37f356d4c308.mp4"
WARNING:urllib3.connectionpool:Connection pool is full, discarding connection: ego4d-unict.s3.eu-central-1.amazonaws.com. Connection pool size: 10
WARNING:urllib3.connectionpool:Connection pool is full, discarding connection: ego4d-unict.s3.eu-central-1.amazonaws.com. Connection pool size: 10
WARNING:urllib3.connectionpool:Connection pool is full, discarding connection: ego4d-unict.s3.eu-central-1.amazonaws.com. Connection pool size: 10
WARNING:urllib3.connectionpool:Connection pool is full, discarding connection: ego4d-unict.s3.eu-central-1.amazonaws.com. Connection pool size: 10
Traceback (most recent call last):
  File "/home/hu/anaconda3/envs/ego4d/lib/python3.9/site-packages/urllib3/connection.py", line 174, in _new_conn
    conn = connection.create_connection(
  File "/home/hu/anaconda3/envs/ego4d/lib/python3.9/site-packages/urllib3/util/connection.py", line 95, in create_connection
    raise err
  File "/home/hu/anaconda3/envs/ego4d/lib/python3.9/site-packages/urllib3/util/connection.py", line 85, in create_connection
    sock.connect(sa)
OSError: [Errno 101] Network is unreachable

**Comment by huaihjn** [comment]
I tried many names when entering region name, such as ap-east-1, us-east-1, us-east-2, et al. but this problem is still exists.

**Comment by huaihjn** [comment]
> 

I didn't successfully download it in the end! if you download it, can you tell me, thank you!

**Comment by gahgdug** [comment]
> I didn't successfully download it in the end! if you download it, can you tell me, thank you!

**Comment by gahgdug** [comment]
> > I tried many names when entering region name, such as ap-east-1, us-east-1, us-east-2, et al. but this problem is still exists.
>
> Did you successfully download it in the end?
I didn't successfully download it! if you download it, can you tell me, thank you!

**Comment by hnuzhy** [comment]
> @devanshk Hi, I tried to set the region to eu-central-1 and used VPN, but still met the same problem, the dataset cannot be downloaded. Besides, I additionally increased the "timeout" to 600, it seems not to work as well. Do you have some other suggestions for downloading the data in China?

Some question! I'm trying to download the `clips` and `annotations` parts. But the connection is not stable. :-(

**Comment by RadishDuck** [comment]
> > @devanshk你好，我尝试将地区设置为 eu-central-1 并使用 VPN，但仍然遇到同样的问题，无法下载数据集。此外，我另外将“超时”增加到 600，似乎也不起作用。你还有其他关于在中国下载数据的建议吗？
> 
> 有问题！我正在尝试下载`clips`和`annotations`部分。但连接不稳定。:-(

您好，请问你们有下载成功吗？我也是一直出现这个报错

**Comment by SJTUwxz** [comment]
Closing this issue for now. Please feel free to re-open it if the problem still persists.
