### ISSUE TITLE
Cannot download lta_models

### ISSUE THREAD

**Issue by shaunak27** [facebookresearch/Ego4d#232]
Hello,

I am unable to download lta_models for the forecasting benchmark and keep running into Error 403 : 

```
Boto 403 Exception For exists: 6c6d81f0-fda8-45a8-89a1-59f1f5f687f0 | lta_slowfast_trf_v2.ckpt
Missing s3 object (ignored for download): 6c6d81f0-fda8-45a8-89a1-59f1f5f687f0 | lta_slowfast_trf_v2.ckpt
```

The command I used for downloading : 

`ego4d --output_directory . --datasets lta_models --benchmarks FHO`

I have verified that credentials are valid. 
Can someone please help me with this?

**Comment by miguelmartin75** [comment]
This now works, please refer to https://github.com/EGO4D/forecasting/issues/29#event-10047444321

```
python -m ego4d.cli.cli -o <out-dir> --datasets lta_models --version v2
```
