### ISSUE TITLE
Cannot submit information to sign Ego4D licence

### ISSUE THREAD

**Issue by s-yamazaki31** [facebookresearch/Ego4d#239]
I'm facing the same issue with #149 that I cannot submit information at https://ego4ddataset.com/. The error message is 'Failed to Fetch'.
Could you help me to solve this?

**Comment by yingsen1** [comment]
encounter same problem

**Comment by yash-s20** [comment]
same issue.

**Comment by reddyav1** [comment]
I'm experiencing the same issue when re-submitting the license form to re-activate the credentials. Any suggestions?

**Comment by chaitanya100100** [comment]
Facing same issue while renewing my EgoExo4D license. Any update on resolving this?

**Comment by SJTUwxz** [comment]
Closing this issue for now. Please feel free to re-open it if the problem still persists.
