### ISSUE TITLE
Error downloading dataset

### ISSUE THREAD

**Issue by runningmanaa** [facebookresearch/Ego4d#242]
When downloading the Ego4d dataset using the command "ego4d --output_directory=”~/ego4d_data"--datasets omnivore_video_swinl --metadata" as mentioned in the README.md file of the Ego4d GitHub repository, you encountered an error after downloading 27.pt files. The error message displayed is "botocore.exceptions.ConnectionClosedError: Connection was closed before we received a valid response from endpoint URL: 'https://ego4d-iiith.s3.ap-south-1.amazonaws.com/'".

**Comment by LeeRoc-China** [comment]
+1

**Comment by heyucchen** [comment]
+1

**Comment by shhuangcoder** [comment]
I have same quention, Have you solved it？

**Comment by heyucchen** [comment]
I have not, but I think the problem may because of GFW.

**Comment by Yuheng2000** [comment]
Have you solved it?

**Comment by SJTUwxz** [comment]
Closing this issue for now. Please feel free to re-open it if the problem still persists.
