### ISSUE TITLE
Missing s3 object for a video in the clips dataset

### ISSUE THREAD

**Issue by nonomanlurker** [facebookresearch/Ego4d#251]
Boto 403 Exception For exists: 964575bd-afec-4815-af83-e93e60d46602 | 964575bd-afec-4815-af83-e93e60d46602.mp4
Missing s3 object (ignored for download): 964575bd-afec-4815-af83-e93e60d46602 | 964575bd-afec-4815-af83-e93e60d46602.mp4

I got this message when downloading clips dataset by
ego4d --output_directory <output_dir> --datasets clips
How could I download it?

**Comment by SJTUwxz** [comment]
Closing this issue for now. Please feel free to re-open it if the problem still persists.
