### ISSUE TITLE
IMU data Download issues

### ISSUE THREAD

**Issue by LuckyMS** [facebookresearch/Ego4d#258]
Dear authors, thank you all again for creating such an interesting dataset. 

But I've run into a problem that I need your help with.

When I downloaded the annotation, everything went fine. But when I try to download the IMU dataset, I find that I can only download about 8% of the data each time, and then the download reports an error. Now the errors I'm getting are:

1. raise EndpointConnectionError(endpoint_url=request.url, error=e)
botocore.exceptions.EndpointConnectionError: Could not connect to the endpoint URL: "https://ego4d-bristol.s3.eu-west-2"

2.[Errno 24] Too many open files: '/Users/ego4d_data/v2/imu'

Each time I encountered a different error, but each time the download stopped automatically at 8%.

I have tried to use the eu-central-1, but this problem still happened. Do you have any suggestions for these problems, thank you very much for your help!

**Comment by miguelmartin75** [comment]
Too many open files sounds like a configuration problem for linux, i.e. try https://stackoverflow.com/a/40716814

as for "could not connect": this may be because of your location

**Comment by SJTUwxz** [comment]
Closing this issue for now. Please feel free to re-open it if the problem persists.
