### ISSUE TITLE
When will the license server be restored?

### ISSUE THREAD

**Issue by ZJWang9928** [facebookresearch/Ego4d#272]
![20231213133429](https://github.com/facebookresearch/Ego4d/assets/30260671/d6f53584-99a9-434b-9ba4-0be5f2e8636a)
The website mentions that the server will be restored on December 11th, but it is still down today. When will it be restored?

**Comment by miguelmartin75** [comment]
It is now restored. If you are still seeing this page please force a refresh:
- In Chrome/Firefox: the shortcut is CMD+SHIFT+R
- In Safari: the shortcut is CMD+SHIFT+E

Alternatively use private browsing/incognito.
