### ISSUE TITLE
Issue about ego-exo4d downloading

### ISSUE THREAD

**Issue by zgchen33** [facebookresearch/Ego4d#281]
Hi, I ran this command ‘egoexo -o data/ --split val’, and the output is below:
```
Filtered 57068 -> 11216 files
Determining what to download ...
100%|██████████████████████████████████████████████████████████████████████████████| 11216/11216 [05:26<00:00, 34.40it/s]
WARN: failed to get stats for 326 files, will skip. [zero_size=0, exceptions=326]
*** BUCKET FAILURES ***:  {'ego4d-iiith'}
Checking current download status ...
......
```
Would the warning about ‘ego4d-iiith’ make my downloading dataset incomplete?
How do I fix this?

**Comment by juliawilkins** [comment]
Hi @zgchen33 did you solve this? Have the same issues.

**Comment by zgchen33** [comment]
@juliawilkins Sorry, I didn't solve this problem. I think the main reason for my failure is I'm living in China. Maybe you can try again, or go to the [forum](https://discuss.ego4d-data.org/) to check some messages.

**Comment by SJTUwxz** [comment]
Closing this issue for now. Please feel free to re-open it if the problem persists.
