### ISSUE TITLE
AssertionError for egoexo4d downloading (no manifest path)

### ISSUE THREAD

**Issue by zhangmuduo** [facebookresearch/Ego4d#284]
When I was trying to download egoexo data, I met the following error:
I guess there's nothing I can do about this, has anyone met similar error before?
Thank you!
![屏幕截图 2023-12-29 164957](https://github.com/facebookresearch/Ego4d/assets/78608255/77d757e8-34d1-488c-bf2a-ea37c9da9a41)

**Comment by miguelmartin75** [comment]
Please ensure you have configured your aws client properly with your dataset token. Run `aws configure` (you may need to `pip install awscli`) then enter your keys, then proceed to download.

If you are located in China, you might find the related issues helpful:
- https://github.com/facebookresearch/Ego4d/issues/223
- https://github.com/facebookresearch/Ego4d/issues/162

**Comment by zhangmuduo** [comment]
> Please ensure you have configured your aws client properly with your dataset token. Run `aws configure` (you may need to `pip install awscli`) then enter your keys, then proceed to download.
> 
> If you are located in China, you might find the related issues helpful:
> 
> * [Hello,  “EndpointConnectionError” occured when I download this dataset in China！ #223](https://github.com/facebookresearch/Ego4d/issues/223)
> * [How can I download it in China？ #162](https://github.com/facebookresearch/Ego4d/issues/162)

Thanks for your reply! I think I had everything set up properly because I am able to download Ego4d dataset but not EgoExo (I'm sure I applied for the right one because when I renewed my Ego4d license, the aws keys are the same for both)
![image](https://github.com/facebookresearch/Ego4d/assets/78608255/78fafada-65fd-4fae-9a1c-cf15ffdb92a3)

**Comment by zhengsipeng** [comment]
the same problem

**Comment by relh** [comment]
I was able to download everything originally but on returning I now get this error. I've tested and the aws credentials work for commands using `ego4d -o ./` just not for `egoexo -o ./`

**Comment by relh** [comment]
Be careful, although the Ego4d and EgoExo license agreements are similar and the credentials are the same, you have to redo the EgoExo one to get access to EgoExo.

This solved the problem for me (I had just renewed Ego4d license agreements)

**Comment by zhangmuduo** [comment]
Everything is working now when I upgraded Ego4D to 1.6.1! Anyway, I renewed my Egoexo license, built the environment again but upgraded Ego4D to latest version and the data could be downloaded now~
Issue closed
