### ISSUE TITLE
Downloading audio only in Ego-Exo4D?

### ISSUE THREAD

**Issue by juliawilkins** [facebookresearch/Ego4d#288]
Hi, thank you so much for the great contributions to this space. I was wondering if there is any way to download only the audio (no video), either take- or unprocessed-level via a CLI argument. I have not found it in the CLI docs. Thank you!

**Comment by miguelmartin75** [comment]
This is not currently possible. Unfortunately, you will have to download the videos and extract the audio yourself as of right now. For the egocentric audio you need to download the raw VRS files `--parts capture_raw_vrs`. There will soon be an update, such that the amount of data you have to download will be reduced, but don't expect this right now. 

 Some questions:
- What's your use case? Are you after narrate & act transcriptions?
- Do you need audio from all cameras, just the egocentric or exocentric?

**Comment by juliawilkins** [comment]
Thanks so much for the quick response @miguelmartin75. This makes sense. 

- My use case is from a purely audio perspective, looking for real-world, "general sounds" multichannel audio. 
- When you say "all cameras" what do you mean exactly? Would that be different from ego+exo all audio? And just to clarify, the egocentric audio is the 7-channel Aria glasses-based audio, and the exo is stereo?

**Comment by miguelmartin75** [comment]
>Question: what audio would I get at with capture_raw_stitched_videos instead of raw vrs?

This is the GoPro recordings (mostly exo). The raw VRS is strictly the egocentric aria device.

**Comment by juliawilkins** [comment]
Hi @miguelmartin75, where is the stereo audio from the GoPro exo recordings? When downloading with `--views exo`, the cam01.mp4 etc. go-pro mp4s don't seem to have audio. Are there any flags to add to get the audio here, or better yet audio-only? Thanks!

**Comment by wisdomikezogwo** [comment]
Hi, I have the same/similar issue, we can get egocentric pre-extracted audio from `--parts take_audio`, however, the exocentric `.mp4`s do not have any audio, how can I obtain the audio for the exocentric videos?

**Comment by miguelmartin75** [comment]
Unfortunately we do not provide that yet exocentric audio. We have this on our backlog cc @devanshk

**Comment by SJTUwxz** [comment]
Closing this issue for now. Please feel free to re-open it if the problem persists.

**Comment by orkrukx** [comment]
Hello,
@miguelmartin75 any update on this? I believe exo cameras still don't provide audio.
