### ISSUE TITLE
Using pyvrs to extract audio and video from EgoExo4D .vrs files

### ISSUE THREAD

**Issue by juliawilkins** [facebookresearch/Ego4d#289]
Hi, wondering if anyone has been able to successfully use [`pyvrs` ](https://github.com/facebookresearch/pyvrs) to extract the audio from the `.vrs` format in EgoExo4D. I also posted an [issue](https://github.com/facebookresearch/pyvrs/issues/18) in their repo but this one seems more active so I thought it was worth a shot. I need to extract, for example, the audio from the .vrs file, as instructed [here](https://facebookresearch.github.io/Aria_data_tools/docs/use-vrs/#extract-image-or-audio-content-to-folders). I tried to `pip install vrs` per their instructions but am not able to use the CLI after this install and am wondering if I'm missing a step here. Please see linked [issue](https://github.com/facebookresearch/pyvrs/issues/18) for more details. Thanks! 

Update -- looks like `pyvrs` does not come with the CLI capability as discussed here: https://github.com/facebookresearch/vrs/issues/132

What is the simplest way to work with these .vrs files without this?

**Comment by miguelmartin75** [comment]
I recommend installing the vrs CLI tool and then extracting audio via the CLI tool. Here are some instructions: https://gist.github.com/miguelmartin75/1261604028db63a1f9a4d0cbd5b605f6
