### ISSUE TITLE
Ego-exo bucket downloading failures 

### ISSUE THREAD

**Issue by juliawilkins** [facebookresearch/Ego4d#293]
I am trying to use the egoexo CLI to download some subsets of the data. For example, the training split:
`egoexo -o <outputfolder> --parts capture_raw_vrs --splits train`

I get the following warnings:
```
Filtered 826 -> 472 files
Determining what to download ...
100%|█████████████████████████████████████████████████████████████████████████| 472/472 [01:36<00:00,  4.91it/s]
WARN: failed to get stats for 430 files, will skip. [zero_size=0, exceptions=430]
*** BUCKET FAILURES ***:  {'ego4d-speac', 'ego4d-penn', 'ego4d-utokyo', 'ego4d-iiith', 'ego4d-georgiatech', 'ego4d-cmu', 'ego4d-indiana', 'ego4d-fair', 'ego4d-minnesota', 'ego4d-university-sa'}
```

Overall, I've only been able to download data from the `unc` and `sfu` university splits - everything else has the bucket failure thrown above.

Any tips on how to get all of the data? Thanks! It would be great to see metadata that shows which parts and splits of the data are available for the different universities and things like that.

**Comment by miguelmartin75** [comment]
Apologies, there will be an announcement on the forums regarding this. We are currently making changes to the dataset. The data you are after (audio) will be available soon as the VRS files trimmed by the take.

**Comment by juliawilkins** [comment]
Thanks a lot @miguelmartin75. Do you have an estimated time of when this would be? Just out of planning curiosity no pressure to commit of course.

**Comment by juliawilkins** [comment]
@miguelmartin75 Just a few clarifications on the above after reading the docs/testing out downloading with `--parts takes`: 

1. The docs read: "Audio -- This is available in the frame aligned videos (for each camera) & VRS files for the egocentric camera (7 microphones) (see above)". I see multiple .mp4s in the `frame_aligned_videos` directories, as well as `aria01_noimagestream.vrs` etc in the root of a sample take directory. Should we expect the audio to be the same between the vrs file extracted audio and if we extract it from the mp4 of the frame aligned videos? 

2. What is the difference between "aria_and_cam01_with_audio.mp4" and "aria01_noimagestream.vrs"?
3. What is the difference between the two .mp4s above and the `frame_aligned_video` .mp4s?
4. I am not seeing IMU data in the VRS files after using the`extract-all` CLI option. Where can we find the IMU data?

**Comment by juliawilkins** [comment]
And one more follow-up sorry 😬 more of a feature request -- if there could be a way to exclude frame_aligned_videos and only download the VRS files that may be of use to folks to help speed up download time/reduce storage space. Thanks again!

**Comment by miguelmartin75** [comment]
You can now download with `--parts take_vrs_noimagestream` for just the VRS files without image streams. Use `--parts take_trajectory` for IMU data.

>What is the difference between "aria_and_cam01_with_audio.mp4" and "aria01_noimagestream.vrs"?
- aria_and_cam01_with_audio.mp4 is a collage of the aria RGB video stream and one exocentric camera (cam01) - which is the "best visible" exocentric camera
- aria01_noimagestream.vrs is just the egocentric recording without video stream data

**Comment by juliawilkins** [comment]
Awesome, thanks so much for this add @miguelmartin75. Super super helpful for the audio only use case!
