### ISSUE TITLE
Cannot download EgoPose part!

### ISSUE THREAD

**Issue by Mahmoud-Ali-FCIS** [facebookresearch/Ego4d#294]
Hi, thank you so much for the great contributions.

I can't download EgoPose. In you website you said that it will be available on Jan 7th, 2024.
Is it available now? If yes, could you please let me know the CLI to download it.
I'm especially focusing on EgoBodyPose.

Thanks.

**Comment by suyogduttjain** [comment]
Hi, 

We are updating some camera poses with better localization, hence the delay. We will release these in about 2 weeks. Will ping here once that is done.

**Comment by Mahmoud-Ali-FCIS** [comment]
Hi,
Is there any update regarding the EgoPose data?
Thanks.

**Comment by isarandi** [comment]
Is there any news about the pose annotation release date? The website still says Jan 7.

**Comment by isarandi** [comment]
It's released now, but I don't have success with using it https://github.com/facebookresearch/Ego4d/issues/331

**Comment by SJTUwxz** [comment]
Closing this issue for now. Please feel free to re-open it if the problem persists.
