### ISSUE TITLE
EgoExo4d No metadata/annotations json files when downloading

### ISSUE THREAD

**Issue by dayoonsuh** [facebookresearch/Ego4d#295]
`egoexo -o /home/smart/Documents/Ego4d/ego4d_data --uids e6f04a5d-0da7-42c9-8b27-4e240319047e`

I am trying to download videos and annotations. However, the code above doesn't fetch any of metadata or annotation json files. It only downloads videos like this:
![image](https://github.com/facebookresearch/Ego4d/assets/89650534/4ec24d0f-f833-40bc-82f2-ae255e96ee1f)

I have tried 
`egoexo -o /home/smart/Documents/Ego4d/ego4d_data --parts metadata annotations --uids e6f04a5d-0da7-42c9-8b27-4e240319047e`
`egoexo -o /home/smart/Documents/Ego4d/ego4d_data --parts annotations --uids e6f04a5d-0da7-42c9-8b27-4e240319047e`
but none of them worked.

How can I get the annotation files?

**Comment by miguelmartin75** [comment]
Annotations are in the `annotations` folder.

We do not partition the annotation files by their uid, as it is pointless since the files are currently small. EgoPose when it is released will have their files partitioned by their uid due to it's size.

**Comment by dayoonsuh** [comment]
> Annotations are in the `annotations` folder.
> 
> We do not partition the annotation files by their uid, as it is pointless since the files are currently small. EgoPose when it is released will have it's files partitioned by take (uid) due to it's size.

Where can I find the `annotations` folder?

**Comment by dayoonsuh** [comment]
> Annotations are in the `annotations` folder.
> 
> We do not partition the annotation files by their uid, as it is pointless since the files are currently small. EgoPose when it is released will have it's files partitioned by take (uid) due to it's size.

![image](https://github.com/facebookresearch/Ego4d/assets/89650534/cf884cd7-d19e-4443-b9a9-e1aa506fdfcf)

This is the file structures. In the download directory `ego4d_data,` there is only `take` folder.

**Comment by miguelmartin75** [comment]
Please run `egoexo -o /home/smart/Documents/Ego4d/ego4d_data --parts annotations` and then check the `annotations` folder under this directory.

**Comment by miguelmartin75** [comment]
Closing, please re-open if this issue still persists.
