### ISSUE TITLE
Unable to Submit License 

### ISSUE THREAD

**Issue by faderani** [facebookresearch/Ego4d#299]
I am trying to submit the form on:
https://ego4ddataset.com/ego4d-license/ 

but I get an error that says 'Load Failed'. 

There are a lot of people posting about the same issue here:
https://discuss.ego4d-data.org/latest

**Comment by suyogduttjain** [comment]
Can you try again, the license server was having some backend issues which we have resolved. Let me know if you still face this issue.

**Comment by devanshk** [comment]
+1; Thanks both for the flag, the license server has now been fixed.

Once you submit the form, you should see a screen similar to this:
![CleanShot 2024-02-07 at 09 42 59@2x](https://github.com/facebookresearch/Ego4d/assets/1356687/09d16806-0815-4f05-b351-1fe93594ede7)

There are a couple of issues that affect the license server and we're setting up flows to make it more robust. The server has been functional during the times between forum comments, and once you get a license - you can use the visualizer in the access email to explore the dataset yourself!

**Comment by kang-jaehyun** [comment]
![image](https://github.com/facebookresearch/Ego4d/assets/60742949/30ba9c0f-a8e2-451a-a4d0-f5767799ccd9)

Today I'm facing this error

**Comment by orrzohar** [comment]
This issue has returned.
