### ISSUE TITLE
Missing audio data for some videos

### ISSUE THREAD

**Issue by TheMVPotato** [facebookresearch/Ego4d#302]
Hi, It appears that two video files in the Ego4D are missing audio data. These video files are named "0d271871-c8ba-4249-9434-d39ce0060e58" and "7d8b9b9f-7781-4357-a695-c88f7c7f7591".
My commands for downloading videos are as follows:
```
ego4d --output_directory="Ego4D/" --datasets full_scale --video_uids 0d271871-c8ba-4249-9434-d39ce0060e58 -y
ego4d --output_directory="Ego4D/" --datasets full_scale --video_uids 7d8b9b9f-7781-4357-a695-c88f7c7f7591 -y
```
I have tried downloading the corresponding videos for both v1 and v2, but they are indeed missing audio data.
If possible, could you please supply the correct versions of the video files with the audio, or inform us how we can obtain the accurate video data? This is crucial for our research and project.

Thank you very much for your assistance and understanding!

**Comment by miguelmartin75** [comment]
Some univeristies redacted their audio, and unfortunately this is one of the cases. Please read the `ego4d.json` file to determine which files have audio and which do not. See the fields here: https://ego4d-data.org/docs/data/metadata/

You should be able to reliably tell which videos have audio via the field `audio_base_denominator`, e.g. `video["audio_base_denominator"] is not None`
