### ISSUE TITLE
Missing takes in relations benchmark

### ISSUE THREAD

**Issue by YuhaoSu** [facebookresearch/Ego4d#306]
Hello, I found there are around 200 takes missed for relations Benchmark. 

More specifically:
1. I first use the default setting to download all data, "egoexo -o addr -y" then again "egoexo -o addr --benchmarks relations -y" to double check that all takes in relation benchmark downloaded.

2. I started by checking how many takes in this benchmark:

train_relation_ann = json.load(open(os.path.join(annotation_dir, "relations_train.json")))
train_relation_objs = train_relation_ann["annotations"]
train_relation_takes = list(train_relation_objs.keys())

test_relation_ann = json.load(open(os.path.join(annotation_dir, "relations_val.json")))
test_relation_objs = test_relation_ann["annotations"]
test_relation_takes = list(test_relation_objs.keys())

results are:
"relations_train.json" ===> returns 977 takes, and "relations_val.json" ===> returns 221 takes. These are 1198 takes

3. I try to iterate each take and do some preprocessing:  
for uid in train_relation_takes:
    annotation = train_relation_objs[uid]
    take_name = annotation['take_name']
    temp_path = os.path.join(take_dir, take_name)
    if os.path.exists(temp_path) is not True:
        uid_str=uid_str+' '+str(uid)
        not_exist_count=not_exist_count+1
        not_exist_uid.append(uid)

for uid in test_relation_takes:
    annotation = test_relation_objs[uid]
    take_name = annotation['take_name']
    temp_path = os.path.join(take_dir, take_name)
    if os.path.exists(temp_path) is not True:
        uid_str=uid_str+' '+str(uid)
        not_exist_count=not_exist_count+1
        not_exist_uid.append(uid)

4. I found there are only 981 takes. And the following takes do not exist:
['80523ee9-f498-4102-85fa-362ae8150d70', '277ebdfc-f235-4fc1-a04f-80756144ecb6', 'f2f93854-2634-449c-b68e-aebf4743ac9f', 'ca1434ea-b787-44ad-a9da-e0f7d5167a35', '4fbe4c60-d4cb-401b-b005-76eeed10c164', 'cea1b20b-6e18-4bb6-87e0-164a2b8c3dc0', '59de58da-2f1a-4ce5-9ccc-ba9e4b114779', 'e317d7f1-3831-41a5-b22a-45b01e0dcc6a', '80f65504-a37a-4c84-8a19-df3bba123326', '5ee00a17-171f-46a4-927b-3aa9d0fe176e', '3ca2798d-cfe3-46c6-a8bc-cc4689bd6d75', '16f0fb5a-5c31-43aa-a292-ea0f7714059b', '0b89efcd-59bf-4f0b-a81a-50dee0b79982', 'b378d186-0587-40ed-afdf-875e6dfb5876', 'ccec2129-83b1-47cc-b179-fc165ac12f25', '1c786ecf-72e9-46ed-978c-34615bf7b378', '1876d795-0c6f-4e0e-8165-e7a0c8a6e77f', '89815623-8ece-4e3c-8879-f1f32b299527', 'bcfb6839-3c09-4d42-9d9c-59042f6ab721', '32d54e67-68d7-4b94-a953-fc3b56a1eb94', '601c9c61-fc2b-4ac2-b3c4-dda557c2563b', 'f1ce9be1-b623-4ce4-84e2-37e9f88eea86', '6cbfa460-72a7-4038-b6af-4305a1cc05dd', '5fd383f1-c8bb-42d7-b98b-7418d99d9bb4', 'f8412ce8-fd3e-4aa9-94b5-a625293dc8a3', '5090a9eb-bfed-44b9-be2d-3219b7c70015', 'bb97189c-c3c2-445b-998a-e65162cb6c93', '9512a137-40b6-49c6-a03d-a3340b9dd277', '3125dca7-b99e-4b2b-8844-2d912619b353', '759aa03c-c8e1-4fcb-8817-85948100ed33', '9357c6f2-9c17-4259-a4bd-7a715e7331e4', 'f36be1f1-491e-4d78-9ce6-d00c4590868b', '9a8dc147-818a-4f38-97c0-12b924033ba5', 'de438b6d-8692-44ea-a6a3-0fbcc459a525', 'e6d8c6ad-31b2-4684-9762-2af1e6709611', '3042b472-99cc-4407-a79e-f76916b95737', '0ffe3d64-3afe-456f-829e-45fc51e50dc4', '2119be6f-9597-46dc-87ca-057cb22570ae', 'c0b7d130-2004-4450-ad94-ea3167bd9fab', '82587f1a-a75d-4462-8971-b62b5c3a633e', 'd8013909-d1be-4b97-831e-b903115eb94c', 'b6cd03ac-d27d-4c9d-841e-02f8f1ed9f3d', '9506c70a-1639-42ea-bbfc-2b9c0f8c9394', '048eccd2-6f53-48cf-8eda-1d633eb74812', '819780c3-97c0-4ac6-b37f-8c66abf8167d', '4ffef14c-5ee1-4955-962c-58eae12a2bf5', 'fba2c124-99ec-40ed-8d6a-46808afe6d98', '89ce47c4-5541-4092-be1b-df86c980fc2e', '87610442-b2dd-437a-ba99-f150a7ae3be8', '29a96621-394a-4411-8404-cae4400df95e', 'c3e71389-75d8-448e-916f-7b62c222d7dd', '0eac0520-a5d8-4a45-bf08-112f5f472850', 'c53daadd-09f0-485b-a51c-1d5679f5fb09', 'aa40670e-4487-4f60-a27b-26f7372ef8e7', '103fc8a3-0e82-43a3-adf8-96bc8b3ac4ef', '0bcb8b46-cc45-4bcb-a627-85633e54e060', '39d48b6a-66e8-4bbb-a596-4461b601cabc', '549e5b97-f93a-4500-8f02-5be13017dce5', '936e7e6e-aa06-4aca-b877-8d5f3c59ecc1', '22877318-1da3-48b6-b7f7-733935ccb682', 'c288cb15-81c7-4463-814f-959c12740499', '69fac17f-6527-493d-8dac-cd3bb61ce23e', 'c16175f5-f990-48a1-9dcc-6a385f108687', '6d0a7c80-ae8c-4673-8f70-c09fd6fbebe8', '816dd81e-93b1-433c-83ff-264ae404a3bf', 'f8bed5fe-3e09-4885-9539-edb4d5b2279a', '8d7646a3-ce7b-425d-b16e-9a63a1166576', 'c05e7fd5-d5f1-4949-872b-2dce2fe88c48', 'e53ae33b-61b6-4c3e-8be0-5696f961704b', 'f0cd03a5-9cd8-4510-87c1-a5c493197b75', 'ef1aee4b-5b24-454e-8c17-ea886f1dbdeb', '8fa671be-2624-4783-8572-5f4b7722b6c0', '8a98cc7f-13f1-4c60-bbd6-6a7f4e9d8d6e', 'cace80a1-42df-4cf4-a1ec-80647638a443', '8e032e92-43a2-4612-8871-94ac5e04057e', '80f082de-9e90-4c33-b4d3-3d3c7ce11e0a', '609123eb-8e83-41f9-9cd5-524fc01f3ea9', 'cfd2c825-45d1-4e59-b33f-b6dff8c174c8', 'd9f94488-4e05-4681-b633-dac5f77664c9', 'ab78a3f2-a3c7-40b5-b2ae-a6a02f327d66', '7d83d5fb-1039-444c-83fb-bcc2f4a7dcf2', '6ad4304b-adf5-4b25-9001-67102157a174', 'cdeef701-ca02-4914-81c9-47a8384f24c6', '5e3c697c-9aef-4686-9055-b34185b21a75', '2ec7440e-5e29-410b-a5f6-40e3a2e45a31', 'b69de073-c157-4cff-8eba-97bfc7baa012', 'ff93ae48-0daa-418c-9d5c-b5b0b6d23efb', 'f3c868c5-25fb-4b49-99de-1edf8a44ee7a', '64b60273-e935-4161-9300-2879b46f5785', '1bf59cee-8985-4d84-a34f-e7c35e492900', '2378c044-8aca-4d1f-9c5e-db2773ae1602', '976e486c-0292-4ee1-bed4-05a3e5b0d6cd', 'ce536dc7-6296-49d5-86da-49267edb3de8', 'ced0e340-b958-4505-badc-c8c2f256c145', '67e74067-407f-4aa9-b8d9-dbac6ea2464f', 'ecd798ef-2839-41f6-8b2b-4b5849c43d11', '9142bb88-ce74-43e8-93aa-a0dcd79735a5', '7dbdb2ef-939a-44a8-a0ee-92f36cc7428b', 'd2b0ee95-2a76-4b69-aebf-3c7e553f8e2b', '98158e6f-2973-47b5-815e-8d8f505d3bc4', 'cc296f88-bb0e-4fcd-b483-07a1b4bcc511', '441b84fd-19e9-4413-949a-c3bbb6a3b16e', 'b65a60e0-f224-4b3d-bf78-ba44e12c4ac1', '8ce327aa-26bb-4cc5-bf2f-d8d2968ecb3e', '2e82ce1e-a2c9-4b5b-897c-8fdc4fde4263', '1f56f60f-9b36-493f-902f-a3bba0fb1b84', '08e08417-f43b-4870-8a26-3f3350bb6197', '214bdc0d-fa50-4a84-b771-c0a7bdeafadc', '506a2aab-775c-435c-8006-918d8fdd997a', '0fd69732-9536-4224-9dcf-dad8855c2d4c', '4e47ec0d-9d0f-410d-81c4-7ba3fb286e75', '4939903a-2c73-4633-ae15-618be39990e7', '393e9b60-504c-4cc7-a90b-eb78dd62d5ff', '31df8578-1fd0-4406-9008-900a88f7990a', '7d59164c-e0bc-4ae0-95c9-733e4c8b0d6a', '71fbd6f0-2df6-4823-9d73-b3fdd3e824e8', '6d84049f-2f5a-4560-8725-9e2182ade954', '1c761444-ece6-46c0-8b95-427f2aa8f405', '6e4ddc67-5e4a-4271-88d9-d9e0f2319159', 'a548b784-dfd2-458f-8131-b36020906d32', 'e46f9a53-7625-4827-8b92-79c958d3524e', '98895ed3-7fc5-4dc0-ae9b-d808971e9334', '73d9fbc1-b6b3-4b3e-89db-3a4de56b924c', 'c216e68c-7483-41d3-b862-d7319b90038e', 'd35a162e-c38e-4017-94d1-539f26651115', '61447268-9963-42ca-9b6b-6fdd2b8332b8', 'f4dead01-fa3d-4aa5-8b59-13a0d9186dd2', '691b6dff-620e-4aab-8302-3a9045be33da', '27cf1b12-9114-46b5-b1fb-66fcef4294f6', 'c04d0f99-3c7f-433d-ba06-95708225826c', 'b7dbb47c-d850-4853-b434-7b20519ea9e5', '55d2990a-537b-429d-9da9-388283b9555e', 'ce914bec-f8c1-46ef-ae28-f1ff030801d1', '33b0f445-e852-4533-87a2-daa650113a80', '51831426-bcac-4946-856a-863fa688ef7d', 'd5193bae-a7f5-4e8a-9c96-09f557c7ea9d', 'df1bcdad-b033-4ac8-bfb9-c62c58a5ac6e', '78e547e6-feae-4adb-9734-d38a4bb34cc9', 'ef2cad65-06b2-4b1a-8956-c387721d2051', '99820fc1-ce50-41ea-bc8d-37b563f9743b', '6449cb24-e14c-4238-9d57-2e0efc4794ba', '2def272d-f803-4feb-95a9-63409b333fd2', 'f092deea-7c8b-4bee-bcd3-a7c22efc3eb3', '389cfa3f-3a4c-4b8f-9535-d7c95ffd594c', '74593ce4-28eb-42e6-8ee0-02f16e704788', '178ef0ae-da45-4982-bbf6-90f2cf8c9ae0', '08504348-4f72-477e-a08f-1050204ae55e', 'fea8a839-1976-4457-b8c7-c722e63faea9', 'a1d2d1f8-907f-4966-858e-06baa2297228', '4cf43506-d0a6-4c42-9136-adb2ecd57411', 'd2b0612f-080c-4bf0-a2c6-2ad121eec990', '47850a65-9719-4770-92e4-e428953addb3', '925ebe22-f97a-4e79-aed3-9873cf461c3c', 'aef3aa96-9883-4119-9ae8-c8b921a98918', '102a45e2-22df-48d4-8c80-2e1d71e6d88b', 'c0049eef-6fb3-4383-9ab3-5e6b892cd843', '4a628bb6-49fa-4cfa-ae74-2b3beac2b095', '289c4873-5bf9-41b9-b784-aba52b54cd4d', 'cde978f7-8fb6-466b-b28a-ee431fe2eb7d', '5ad8e62d-726c-430a-9849-6f5d3ba3704c', '7dc2f406-0ea7-48c9-9854-e60273300eaf', '975bbcd5-fbb3-4323-b9a8-a9b476887c18', '20444f75-29b0-47d1-a7e5-3b630db8a39c', '319a9983-f70c-4224-a3a7-33338c8a9f35', 'b6a97017-0d95-4992-97d2-7195bf85acd3', 'e481c982-5bd0-49eb-9446-6ec753d7f366', '35d732a8-f4ae-42d6-96ca-5ee7ef16639a', '636eaa0b-d65d-4b25-bbdd-1065f84ef89e', 'f1393608-1ae0-4170-a03c-68a662257310', '750d4100-59e5-4a2c-bd31-b1adff39738f', 'f3a93a58-cf60-4364-a6be-03a4ed77fc0a', '21dae23d-7488-4efb-b40c-16a6ad3b984f', 'dde3ddc3-403e-4935-a7f7-eca575e05b99', '20d8ece4-05f2-44aa-83a6-14e66328c1e4', 'cb247f6d-662e-41cf-ae2f-eb19b1a145ff', '111c8b18-f7da-4613-8821-98b5ca61eaf5', 'aee495e1-b008-4a06-b09f-1209ab702ea2', '06434a91-b0b1-4cd9-860e-d16fb4bd8331', '0f79cfa6-4ac9-4bbd-ad14-56555ff1daf4', '4a7b1cc0-93d7-4e0b-95e2-75a8c126d971', '0a1f4df9-eb82-4015-887a-658e82af65b2', '7d2996e6-72c5-4413-b285-d291d174c373', '6f942bbd-acc8-4ec1-8758-89029b391cda', '208b98b1-a2e1-4a5b-a6b8-c145acefd5a4', '657ac923-eab5-4e75-9c5d-0c52da9bc1c4', '16f64889-512e-400f-9911-c2e9c90adb6c', '304ac782-8ebc-4ffc-929c-a0d44ce19f45', '853d087c-f00d-4659-8d63-f5052fb465a6', '5811df02-cfb8-4519-a631-2fe68162ffd0', '3de3b002-e358-49ab-a096-eedc37d279d0', '202fa030-efac-43df-bab2-c9fe558b7155', '15797b88-5b11-4d86-ab94-26a26163af5a', 'f92f8261-8a23-4b05-b94f-965d1e66adbc', '294f49e6-55f5-4eed-b66f-6f86b1c1b353', '4b029f02-237c-44fe-8495-881f5ac0a8b2', '769f2445-6a66-41b7-b62d-4a2ed600f357', '16dc75b8-458c-463e-83b4-3ddd38c024fe', 'e3cf5c2c-5e11-4ff6-8026-c9bb431bd54e', 'f99a7d0f-88a5-477b-9f29-6ef98d52de17', 'bb3a1a8c-c14b-48e9-bfc9-20d5eb33d891', '551082fb-7afe-4477-8625-9c357ba39093', 'dfa6811a-2db6-41ce-9260-c852a4780ffe', '1900770b-de9d-4a9c-a06c-0a1636b92ed0', '99e3335c-5a7e-44d0-b991-85387c282cd3', '1c9dae64-e7d0-415b-ae95-99ee78eaae90', '9de15300-fbcb-4838-be91-6b646be2646e', '8000dfb2-accb-4bb8-abfb-cc2d677d0b2f', '6e5211e1-72d8-4032-ba56-b4095c0f2b36', '96bee032-4903-4d47-ade4-6535f0590fe2', '6effa4db-4cf2-4de5-8295-59366ede9ca4', 'd300ece0-41a7-4707-a08b-2f48aedeb75f', 'af223382-86df-43f7-989b-331fe0436810', '9a533209-1d5e-4382-a2f8-c109605845e3', 'd4a8fe94-6f62-42cb-aaaa-c2f9a056620e', '05367d8f-6e4b-4373-b5ad-ea192014bcaa', '2e00eb80-4fd0-4ba5-bcbb-5e671d7f3627', 'f926d185-62b9-4838-9269-d7f4ac776f2a']

I again use download command with uids above and did not find any additional takes to download, could you let me know where I went wrong? Thank you!

Best,
Yuhao

**Comment by miguelmartin75** [comment]
Some takes were redacted. Please refer to this post on the forums: https://discuss.ego4d-data.org/t/ego-exo4d-dataset-changes-quality-issues-future-update/463

**Comment by miguelmartin75** [comment]
Closing as V2 is released, there is no longer missing takes.
