### ISSUE TITLE
Quits when trying to download with CLI

### ISSUE THREAD

**Issue by orrzohar** [facebookresearch/Ego4d#313]
egoexo -o /pasteur/data/Video-STaR/EgoExo4D

ERROR: some supplied parts (['captures']) do not exist
NOTE: did you spell the parts correctly?
Quitting ...

**Comment by miguelmartin75** [comment]
This issue should be resolved now. Apologies for the inconvenience. 

Please also upgrade to `1.7.1` the CLI download should be much faster to start the download now. Additionally, I have update the docs to include more information about the size of each part: https://docs.ego-exo4d-data.org/download/

I've also added `--parts all` incase you want to download everything.

**Comment by chaitanya100100** [comment]
@miguelmartin75 , I have updated to 1.7.1 and now I can't download captures. Here is terminal log:

```
>>> egoexo -o <dir> --parts captures -y
Obtaining part metadata ...
100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:03<00:00,  3.82s/it]
Done
Checking current download status ...
100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 8061/8061 [00:01<00:00, 6761.24it/s]
Downloaded: 100.000% = 40.622GiB / 40.622GiB (8046 / 8061 files) downloaded
Preparing output directories ...
100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1574/1574 [00:00<00:00, 4786.23it/s]
Downloading ...
Fetching: 0.000GiB
  0%|                                                                                                                                  | 0.00/25.6k [00:00<?, ?iB/s]
  WARN: failed to fetch 15 files [integrity=0, exceptions=15]
Please retry the download (... returning with error code 2)
```

**Comment by orrzohar** [comment]
It now gets killed instead of downloading the data 

<img width="1512" alt="image" src="https://github.com/facebookresearch/Ego4d/assets/108689663/daab7822-e8fe-465f-8e9c-a5765662aabb">
