### ISSUE TITLE
Cannot submit the license agreement

### ISSUE THREAD

**Issue by kylemin** [facebookresearch/Ego4d#314]
It's been a few days.
![image](https://github.com/facebookresearch/Ego4d/assets/29569976/d646e3c4-aa80-45d7-b224-ee7cb8ecd51c)

**Comment by suyogduttjain** [comment]
@kylemin  Requesting the team to look into it.

**Comment by devanshk** [comment]
Hi @kylemin, I've tested this a few times this week and it's been working for me. Can you try again, and if it doesn't work - can you send a screenshot of your form before-submission to dkukreja@meta.com so we can try and replicate it?

![Untitled](https://github.com/facebookresearch/Ego4d/assets/1356687/3b099aaa-198a-489d-bc9a-6f34b1acbf8a)

**Comment by kylemin** [comment]
Now it works fine! Thank you all
