### ISSUE TITLE
Project Website Down

### ISSUE THREAD

**Issue by jiadingfang** [facebookresearch/Ego4d#318]
Hi,

I'm excited about the new release of EGO-EXO-4D. But it seems that both the EGO4D and EDO-EXO-4D websites are down (https://ego-exo4d-data.org/) and (https://ego4d-data.org/docs/).

Is there a plan to fix them?

**Comment by SJTUwxz** [comment]
Closing this issue for now. Please feel free to re-open it if the problem persists.
