### ISSUE TITLE
License page failed 

### ISSUE THREAD

**Issue by tiangeluo** [facebookresearch/Ego4d#319]
<img width="994" alt="Screenshot 2024-04-03 at 10 17 51 PM" src="https://github.com/facebookresearch/Ego4d/assets/11552657/74ee4812-31cc-4652-959f-17acb8a7f248">

Could you please help fix the license page?

**Comment by sunwhw** [comment]
So how to sovle  it?  I also get stuck with the problem.

**Comment by lixinghe1999** [comment]
The license page is working now, however, I found I can't use my registered email. I have to change the email instead.

**Comment by SJTUwxz** [comment]
Closing this issue for now. Please feel free to re-open it if the problem persists.
