### ISSUE TITLE
Why I set Access ID and Access Key for EgoExo4D but still can't download the hand pose datasets?

### ISSUE THREAD

**Issue by lin-nie** [facebookresearch/Ego4d#323]
Hi, what I want to ask is **I am not in China** and I follow the instruction to set the Access ID and Access Key.

When I use the command: **egoexo -o $output_datasets_dir --parts annotations metadata --benchmarks hand_pose**
But still I get:

![image](https://github.com/facebookresearch/Ego4d/assets/66514313/32c4a572-1c7f-487a-bc6e-ff2f0532e8eb)

Can anyone help me?

**Comment by lin-nie** [comment]
Hope to help everyone, don't use personal AWS Access Key ID.

**Comment by sunwhw** [comment]
> Hope to help everyone, don't use personal AWS Access Key ID


so use the access key got from after applying the data?
