### ISSUE TITLE
Cannot download the "captures" part in ego-exo-4d

### ISSUE THREAD

**Issue by jianwang-mpi** [facebookresearch/Ego4d#326]
Hello,

Recently I tried to update the ego-exo-4d dataset and I used the following command:

 egoexo -o egoexo --release v2 --parts captures

However, there was an error as following:

![image](https://github.com/facebookresearch/Ego4d/assets/13883222/61816677-0d49-4ab1-a57a-1c0ffb5c8954)

Can you help me to solve this?

Thanks,

Jian Wang

**Comment by miguelmartin75** [comment]
Please ignore these 15 files. I believe they are of zero-size. You can upgrade the `ego4d` pip package to `1.7.2` to confirm this.

**Comment by jianwang-mpi** [comment]
No, they are not zero-size. The total size is 25.6 KB. I upgraded the ego4d package to 1.7.2 and re-downloaded the captures part. However, the exact same issue happens again.

**Comment by miguelmartin75** [comment]
Yes you are correct. I looked more deeply into this issue. These are post survey files that we have redacted due to the proficiency benchmark. 

I am currently updating the downloader metadata. Please ignore this error.

**Comment by miguelmartin75** [comment]
I have updated the CLI download metadata. You should not face this issue anymore. Apologies for the inconvenience and thank you for flagging this issue.

**Comment by jianwang-mpi** [comment]
Thanks for your message. I have another question:

If I re-run the script "egoexo -o egoexo --release v2" and it does not download anything. Does it mean that I have already completed the downloading?

Thanks!
