### ISSUE TITLE
"failed to fetch 61050 files [integrity=0, exceptions=61050]" for Ego-Exo4D

### ISSUE THREAD

**Issue by prismformore** [facebookresearch/Ego4d#329]
I ran `egoexo -o /mnt/datasets/egoexo_data` and some files cannot be downloaded, it shows this error message after I ran the command again:

```
Expected size of downloaded files is 4175.8 GiB (61050 files). Do you want to start the download? ([y]/n): y
Preparing output directories ...16647/16647 [00:21<00:00, 779.86it/s]
Downloading ...
Fetching: 4175.838GiB
0%|                                                       | 0.00/4.08T [00:00<?, ?iB/s]
WARN: failed to fetch 61050 files [integrity=0, exceptions=61050]
Please retry the download (... returning with error code 2)
```

**Comment by likanchuan09171** [comment]
I ran into the same problem. Did you manage to solve it?

**Comment by YijunHu2** [comment]
I ran into the same problem. Did you manage to solve it?

**Comment by Simon1059770342** [comment]
I ran into the same problem. Did you manage to solve it?

**Comment by YijunHu2** [comment]
> I ran into the same problem. Did you manage to solve it?

You could try to use VPN to download the dataset if you are in China, this worked for me.
