### ISSUE TITLE
Only pose information loaded when choosing to download all the annotations of egoexo4d

### ISSUE THREAD

**Issue by likanchuan09171** [facebookresearch/Ego4d#333]
Hello,

I run a command like 'egoexo -o /data/ --parts annotations metadata captures expert_commentary --uids 83ab91c7-ba47-45be-bd19-38d9246baae4 -y', but only annotations/ego_pose is downloaded, while there are no other annotations e.g. 
narrations and expert_commentary. 

I believe that these parts of this take exist , as in the visualizing website: 'https://visualize.ego4d-data.org/iiith_cooking_11_1?v=%22EgoExo+v1%22&p=3&s=%2283ab91c7-ba47-45be-bd19-38d9246baae4%22'.

Did I misunderstand the usage or is something wrong with the CLI downloader? 

Can you help me to solve this?

Thanks,

LKC

**Comment by miguelmartin75** [comment]
Yes this may be a bug, I will look into this. 

To unblock yourself, are you able to download those parts without the filter? They should not take much disk space.

**Comment by likanchuan09171** [comment]
I have tried commands filtered by splits like 'egoexo -o /data --parts annota
tions --splits val -y'. It ends with a error as below 
![image](https://github.com/facebookresearch/Ego4d/assets/170174077/e9da7b03-7918-447d-82fc-85ac357826d8)

This time there are some annotation files left like 'atomic_descriptions_val.json.F14eE010' 'expert_commentary_train.val.73aB0F71'.
Manually converting filenames to json results in meaningful content, but some of their lines are incomplete and therefore do not constitute a proper json format.
![image](https://github.com/facebookresearch/Ego4d/assets/170174077/34c62723-6ab1-43d8-8f1e-9c1b96a76ea6)

Next I'll try if these annotations could be downloaded fully without any filters.

**Comment by miguelmartin75** [comment]
Those are partial files when downloading from S3. Use `-d` on the CLI to delete auxiliary files (be careful with this option and avoid using filters)

**Comment by pdxdydz** [comment]
Hi,
I'm having the same issue when downloading with:
"egoexo -o sfu_cooking015_2/ --uids 9bc33576-bcb6-42a5-b040-3220456f268f --parts all"
Only annotations, features, and takes are downloaded, and under annotations/ there is only ego_pose/.
The take_uid was copied from the official visualization site, and it seems to include the relations and keysteps parts.
Should I try another region or use a VPN? I'm in China.

**Comment by pdxdydz** [comment]
> Hi, I'm having the same issue when downloading with: "egoexo -o sfu_cooking015_2/ --uids 9bc33576-bcb6-42a5-b040-3220456f268f --parts all" Only annotations, features, and takes are downloaded, and under annotations/ there is only ego_pose/. The take_uid was copied from the official visualization site, and it seems to include the relations and keysteps parts. Should I try another region or use a VPN? I'm in China.

I was able to resolve the issue by filtering downloads based on benchmarks and parts instead of UIDs.
