### ISSUE TITLE
Cannot find ego4d multi-view videos

### ISSUE THREAD

**Issue by YuDeng** [facebookresearch/Ego4d#344]
Hi, thanks for sharing this wonderful dataset!

I wonder how to locate videos shot with multi-view cameras in ego4d. I've checked the meta data (ego4d.json) but did not find any label to tell whether a video is multi-view or not (I only find is_stereo). 

Besides, I wonder if there is any overlap between egoexo-4d videos and ego4d multi-cam videos.

**Comment by miguelmartin75** [comment]
Please refer to https://ego4d-data.org/docs/data/unprocessed_data/

You want `ego4d  -o <out_dir> --datasets components/3rd_person_video`

> I wonder if there is any overlap between egoexo-4d videos and ego4d multi-cam videos.
No, there is no overlap. They were collected with a different procedure.

**Comment by markomih** [comment]
Hi @miguelmartin75 , I get the following error when running your command (`ego4d --output_directory="~/ego4d_data" --datasets components/3rd_person_video`):

> Traceback (most recent call last):
>   File "/home/marko/anaconda3/envs/2dgs/bin/ego4d", line 8, in <module>
>     sys.exit(main())
>   File "/home/marko/anaconda3/envs/2dgs/lib/python3.7/site-packages/ego4d/cli/cli.py", line 251, in main
>     main_cfg(config)
>   File "/home/marko/anaconda3/envs/2dgs/lib/python3.7/site-packages/ego4d/cli/cli.py", line 120, in main_cfg
>     validated_cfg.version, dataset, download_path, s3
>   File "/home/marko/anaconda3/envs/2dgs/lib/python3.7/site-packages/ego4d/cli/manifest.py", line 159, in download_manifest_for_version
>     _manifest_object(version, dataset, s3).download_file(str(download_path))
>   File "/home/marko/anaconda3/envs/2dgs/lib/python3.7/site-packages/boto3/s3/inject.py", line 367, in object_download_file
>     Config=Config,
>   File "/home/marko/anaconda3/envs/2dgs/lib/python3.7/site-packages/boto3/s3/inject.py", line 197, in download_file
>     callback=Callback,
>   File "/home/marko/anaconda3/envs/2dgs/lib/python3.7/site-packages/boto3/s3/transfer.py", line 405, in download_file
>     future.result()
>   File "/home/marko/anaconda3/envs/2dgs/lib/python3.7/site-packages/s3transfer/futures.py", line 103, in result
>     return self._coordinator.result()
>   File "/home/marko/anaconda3/envs/2dgs/lib/python3.7/site-packages/s3transfer/futures.py", line 266, in result
>     raise self._exception
>   File "/home/marko/anaconda3/envs/2dgs/lib/python3.7/site-packages/s3transfer/tasks.py", line 269, in _main
>     self._submit(transfer_future=transfer_future, **kwargs)
>   File "/home/marko/anaconda3/envs/2dgs/lib/python3.7/site-packages/s3transfer/download.py", line 357, in _submit
>     **transfer_future.meta.call_args.extra_args,
>   File "/home/marko/anaconda3/envs/2dgs/lib/python3.7/site-packages/botocore/client.py", line 553, in _api_call
>     return self._make_api_call(operation_name, kwargs)
>   File "/home/marko/anaconda3/envs/2dgs/lib/python3.7/site-packages/botocore/client.py", line 1009, in _make_api_call
>     raise error_class(parsed_response, operation_name)
> botocore.exceptions.ClientError: An error occurred (403) when calling the HeadObject operation: Forbidden
>
