### ISSUE TITLE
how to download Full Primary Dataset?

### ISSUE THREAD

**Issue by WannaSir** [facebookresearch/Ego4d#346]
i want to download the Full Primary Dataset in [this](https://ego4d-data.org/docs/start-here/),but there is no method to download it,

**Comment by miguelmartin75** [comment]
Use the command

```
ego4d --output_directory="~/ego4d_data" --datasets full_scale annotations
```

**Comment by SJTUwxz** [comment]
Closing this issue for now. Please feel free to re-open it if the problem persists. Thank you!
