### ISSUE TITLE
"Failed to fetch" error

### ISSUE THREAD

**Issue by nguyentthong** [facebookresearch/Ego4d#351]
Thank you for your interesting work! I have filled in the form to sign the license. However, it gave the error "Failed to fetch". Can you help me look into the problem?

![image](https://github.com/user-attachments/assets/c0015963-8187-4733-a576-e59dbcbcb054)

Thank you so much!

**Comment by oximi123** [comment]
I have the same problem. Can anyone fix this error?

**Comment by seohyun8825** [comment]
Same here, when trying to submit information as individual.

**Comment by rootpine** [comment]
I also have the same problem.

**Comment by nguyentthong** [comment]
I still have the problem, can you help us? @miguelmartin75 @devanshk

**Comment by rootpine** [comment]
[
![20241015101255](https://github.com/user-attachments/assets/e5d0c8df-81fc-4441-9598-9928dfd27988)
](url)

**Comment by zhangyl4** [comment]
![image](https://github.com/user-attachments/assets/b5bc97b2-121e-4b2a-b450-eed67f782a06)

**Comment by qingxinxia** [comment]
can anyone help us?

**Comment by seohyun8825** [comment]
> can anyone help us?

 waited a bit and tried again at a different time, and it worked

**Comment by rootpine** [comment]
> waited a bit and tried again at a different time, and it worked

It's still not working for me.

**Comment by qingxinxia** [comment]
> > can anyone help us?
> 
> waited a bit and tried again at a different time, and it worked

But even signed on dropbox, I haven't received the access key yet...

**Comment by SJTUwxz** [comment]
Closing this issue for now. Please feel free to re-open it if the problem persists. Thank you!
