### ISSUE TITLE
Data Access Problem

### ISSUE THREAD

**Issue by seohyun8825** [facebookresearch/Ego4d#353]
Thank you for sharing your work.

I attempted to access the datasets, but received the following message:

"Unfortunately, your request has been denied. The following reason was provided: Full home/personal address including house number and street name is required."

However, when I try to enter my full address, I receive this error:

"Value for editable custom_field 'Address' is too long. Approximate max length: 75 characters per line, 1 line(s) (depending on character size). See https://developers.hellosign.com/docs/templates/walkthrough/#using-long-text-in-custom-fields."

Could you provide guidance on how to resolve this issue?

**Comment by devanshk** [comment]
Hi @seohyun8825, the license server unfortunately cannot hold addresses longer than 75 characters. Can you please try a shortened version of the address that still includes all components? If that's not possible, please reopen this issue and we'll follow up to get you access.
