### ISSUE TITLE
No response after signing the license 3 days ago

### ISSUE THREAD

**Issue by ligengen** [facebookresearch/Ego4d#356]
Hello,
I signed the license agreement for the ego4d and egoexo4d datasets on Oct 14, but have not received any response. The instructions mentioned a 2-day response time, which is now 3 days. Could you please update me on the status? Thank you!

**Comment by qingxinxia** [comment]
Hello, did you receive the access code now?

I also signed the ego4dexo 3 days ago, and nothing was received.

**Comment by ligengen** [comment]
> Hello, did you receive the access code now?
> 
> I also signed the ego4dexo 3 days ago, and nothing was received.

No unfortunately.

**Comment by ligengen** [comment]
Hi team @miguelmartin75 @devanshk,

It's been a week since I signed the license and no response at all yet. I tried to re-sign, but I got "NetworkError when attempting to fetch resource." Could you please help me figure this out? Thank you!

**Comment by RayTzeng** [comment]
Hi @miguelmartin75 @devanshk. I also faced the similar "failed to fetch" issue. Could you please help this out?
