### ISSUE TITLE
Dataset Download and Missing Takes Issue

### ISSUE THREAD

**Issue by YijunHu2** [facebookresearch/Ego4d#360]
Hi, I greatly appreciate the contribution of this dataset.
However, when I attempted to run the following command:
`egoexo -o /data/seg/Ego-Exo4D/ --benchmarks correspondence --yes`
the download process proceeded smoothly until an error occurred:

> Fetching: 399.840GiB 0%|                                               | 0.00/400G [00:00<?, ?iB/s]
WARN: failed to fetch 2585 files [integrity=0, exceptions=2585]
Please retry the download (... returning with error code 2)

I retried the download several times, but the error persisted. （This issue was ultimately resolved by using a VPN, as I'm located in China.）
So I examined the dataset's annotations, including relations_train.json, and noticed that some "takes" listed were not present in takes.json, which records the access paths for each take.
Additionally, I tried running the command:
`egoexo -o /data/seg/Ego-Exo4D/ --uids 1c786ecf-72e9-46ed-978c-34615bf7b378`
where 1c786ecf-72e9-46ed-978c-34615bf7b378 is a UID found in relations_train.json but not in takes.json. The terminal output showed:
> Obtaining part metadata ...
100%|█████████████████████████████████████████████| 6/6 [01:37<00:00, 16.28s/it]
Done
Filtered 93294 -> 0 files
Checking current download status ...
0it [00:00, ?it/s]
Downloaded: 100.000% = 0.000GiB / 0.000GiB (0 / 0 files) downloaded
Everything has been downloaded. Bye.

**Comment by SJTUwxz** [comment]
Hi, thank you for your interest in our dataset! 

Regarding your question about “why some takes have annotations in `relations_train.json` but do not exist in `takes.json`:

These takes were initially annotated, but after the process of quality control, we found that they do not contain interesting activity. They were mostly about camera setups or transitions. As a result, in our final release of the dataset, we have excluded those dropped takes, thus in takes.json, these dropped takes do not exist.

So our recommendation would be to ignore these takes (ones that are missing in the takes.json) when working with the annotation files.  

Please let me know if you have further questions!

**Comment by dhkim0225** [comment]
@SJTUwxz 
Thank you for the detailed explanation. 
But, I really need the dropped takes. 
Is there any way to download it? 
thank you (#362)
