### ISSUE TITLE
Request for Correspondence Baseline Code

### ISSUE THREAD

**Issue by YijunHu2** [facebookresearch/Ego4d#369]
Hi there,

I hope you're doing well! I was wondering if you could share the code for the baselines for EgoExo4D, as it would be extremely helpful for our experiments in the following work.

Thank you in advance!

**Comment by suyogduttjain** [comment]
They are available here: https://github.com/EGO4D/ego-exo4d-relation

We will improve our documentation page to highlight this more cleary.

Please close the issue if this resolves your question

**Comment by YijunHu2** [comment]
> They are available here: https://github.com/EGO4D/ego-exo4d-relation
> 
> We will improve our documentation page to highlight this more cleary.
> 
> Please close the issue if this resolves your question

Thanks for your help!
