### ISSUE TITLE
Fail to download the dataset, 403 Fobidden

### ISSUE THREAD

**Issue by LiJunscs** [facebookresearch/Ego4d#372]
When I try to download the ego4d dataset, I encounter the follow problem. And I'm sure I configured the aws 
![aws](https://github.com/user-attachments/assets/ce6096a5-11f1-4b40-a334-f8200d937e49).
And I also use the credentials granted by the organization, which is granted yesterday.

How to resovle the problem?

```python
ego4d --output_directory="./" --datasets  annotations --metadata

Datasets to download: {'annotations'}
Download Path: v2
Downloading Ego4D metadata json..
Traceback (most recent call last):
  File "/home/lijun2/miniconda3/envs/lmms-eval/bin/ego4d", line 8, in <module>
    sys.exit(main())
  File "/home/lijun2/miniconda3/envs/lmms-eval/lib/python3.10/site-packages/ego4d/cli/cli.py", line 251, in main
    main_cfg(config)
  File "/home/lijun2/miniconda3/envs/lmms-eval/lib/python3.10/site-packages/ego4d/cli/cli.py", line 74, in main_cfg
    metadata_path = download_metadata(
  File "/home/lijun2/miniconda3/envs/lmms-eval/lib/python3.10/site-packages/ego4d/cli/manifest.py", line 199, in download_metadata
    _metadata_object(version, s3).download_file(str(download_path))
  File "/home/lijun2/miniconda3/envs/lmms-eval/lib/python3.10/site-packages/boto3/s3/inject.py", line 361, in object_download_file
    return self.meta.client.download_file(
  File "/home/lijun2/miniconda3/envs/lmms-eval/lib/python3.10/site-packages/boto3/s3/inject.py", line 192, in download_file
    return transfer.download_file(
  File "/home/lijun2/miniconda3/envs/lmms-eval/lib/python3.10/site-packages/boto3/s3/transfer.py", line 406, in download_file
    future.result()
  File "/home/lijun2/miniconda3/envs/lmms-eval/lib/python3.10/site-packages/s3transfer/futures.py", line 103, in result
    return self._coordinator.result()
  File "/home/lijun2/miniconda3/envs/lmms-eval/lib/python3.10/site-packages/s3transfer/futures.py", line 264, in result
    raise self._exception
  File "/home/lijun2/miniconda3/envs/lmms-eval/lib/python3.10/site-packages/s3transfer/tasks.py", line 265, in _main
    self._submit(transfer_future=transfer_future, **kwargs)
  File "/home/lijun2/miniconda3/envs/lmms-eval/lib/python3.10/site-packages/s3transfer/download.py", line 352, in _submit
    response = client.head_object(
  File "/home/lijun2/miniconda3/envs/lmms-eval/lib/python3.10/site-packages/botocore/client.py", line 569, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/home/lijun2/miniconda3/envs/lmms-eval/lib/python3.10/site-packages/botocore/client.py", line 1023, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (403) when calling the HeadObject operation: Forbidden
```

**Comment by LiJunscs** [comment]
I just make a mistake when I input the key

**Comment by hey0chen** [comment]
Hi, @LiJunscs 
I'm facing the same issue, can you share your specific solution? Thanks!

**Comment by LiJunscs** [comment]
> Hi, [@LiJunscs](https://github.com/LiJunscs) I'm facing the same issue, can you share your specific solution? Thanks!

https://ego4ddataset.com/ego4d-license/

Apply the license in the website, do not use the private license.

**Comment by hey0chen** [comment]
> > Hi, [@LiJunscs](https://github.com/LiJunscs) I'm facing the same issue, can you share your specific solution? Thanks!
> 
> https://ego4ddataset.com/ego4d-license/
> 
> Apply the license in the website, do not use the private license.

I just got my licesnse yesterday, and I can use my access id on [visualize.ego4d-data.org/login](https://visualize.ego4d-data.org/login). However, this problem still persists.

**Comment by LiJunscs** [comment]
> > > Hi, [@LiJunscs](https://github.com/LiJunscs) I'm facing the same issue, can you share your specific solution? Thanks!
> > 
> > 
> > https://ego4ddataset.com/ego4d-license/
> > Apply the license in the website, do not use the private license.
> 
> I just got my licesnse yesterday, and I can use my access id on [visualize.ego4d-data.org/login](https://visualize.ego4d-data.org/login). However, this problem still persists.

Maybe there typo? Such as upper case I or lower case L> I'm not sure. My problem is this at that time. Or you can change the region to that near you

**Comment by hey0chen** [comment]
> > > > Hi, [@LiJunscs](https://github.com/LiJunscs) I'm facing the same issue, can you share your specific solution? Thanks!
> > > 
> > > 
> > > https://ego4ddataset.com/ego4d-license/
> > > Apply the license in the website, do not use the private license.
> > 
> > 
> > I just got my licesnse yesterday, and I can use my access id on [visualize.ego4d-data.org/login](https://visualize.ego4d-data.org/login). However, this problem still persists.
> 
> Hi, I'm facing the same issue, do you address this solution?

I found that it was a network problem of my machine. When I ran it on the local windows, it could run successfully. Hope it can help you!

**Comment by PotatoMine236** [comment]
> > > > > Hi, [@LiJunscs](https://github.com/LiJunscs) I'm facing the same issue, can you share your specific solution? Thanks!
> > > > 
> > > > 
> > > > https://ego4ddataset.com/ego4d-license/
> > > > Apply the license in the website, do not use the private license.
> > > 
> > > 
> > > I just got my licesnse yesterday, and I can use my access id on [visualize.ego4d-data.org/login](https://visualize.ego4d-data.org/login). However, this problem still persists.
> > 
> > 
> > Hi, I'm facing the same issue, do you address this solution?
> 
> I found that it was a network problem of my machine. When I ran it on the local windows machine, it could run successfully. Hope it can help you!

Thank you for your answer, I have solved the problem. The data I applied for Ego-Exo4D was accessed by mistake. ฅ^•ﻌ•^ฅ

**Comment by PotatoMine236** [comment]
> > > > > Hi, [@LiJunscs](https://github.com/LiJunscs) I'm facing the same issue, can you share your specific solution? Thanks!
> > > > 
> > > > 
> > > > https://ego4ddataset.com/ego4d-license/
> > > > Apply the license in the website, do not use the private license.
> > > 
> > > 
> > > I just got my licesnse yesterday, and I can use my access id on [visualize.ego4d-data.org/login](https://visualize.ego4d-data.org/login). However, this problem still persists.
> > 
> > 
> > Hi, I'm facing the same issue, do you address this solution?
> 
> I found that it was a network problem of my machine. When I ran it on the local windows machine, it could run successfully. Hope it can help you!

Thank you for your response. I've resolved the issue — I mistakenly accessed the Ego4D dataset instead of the Ego-Exo4D data I requested. Thanks again for your help! ฅ^•ﻌ•^ฅ
