### ISSUE TITLE
[Suggesstion] Better README for data downloading + pip package installment

### ISSUE THREAD

**Issue by Ariostgx** [facebookresearch/Ego4d#44]
Hi,

Thanks for the great work!

I tried to download the dataset following the page here: https://ego4d-data.org/docs/start-here/#cli-download. Which directed me to https://github.com/facebookresearch/Ego4d/blob/main/ego4d/cli/README.md.

After I configured AWS, I tried the next step

`python -m ego4d.cli.cli --output_directory="~/ego4d_data" --datasets full_scale annotations`

However, I find that this requires me to install the package "ego4d", which a new user doesn't expect to see. I also didn't see the install instruction in the main page: https://github.com/facebookresearch/Ego4d. I only realized that this is a pip package by seeing the setup.py file in the main folder.

I think it would be better if you can provide a one-line instruction for installation for the pip package itself. This would make the user experience much smoother. Thanks!

**Comment by v-iashin** [comment]
In case someone wonders what the command is: 
`pip install git+https://github.com/facebookresearch/Ego4d.git`

**Comment by ebyrne** [comment]
Please install using easyinstall: `python setup.py install`

We'll add it to the README (and a requirements.txt if you prefer).  Thanks for the suggestion!
