### ISSUE TITLE
[Social Interactions] "Looking at me" all are labelled as false

### ISSUE THREAD

**Issue by spongezhang** [facebookresearch/Ego4d#52]
Hi Ego4D team,

Thank you so much for releasing this benchmark! It's great!

I downloaded the annotation file yesterday. After taking a short scan of the data, I've noticed that for av_train.json and av_val.json, all _"social_segments_looking" are labeled as false_. It's a bit odd, since it should contain both true and false labels. Would you please help take a look at that and see if I'm missing anything?

Best,

**Comment by spongezhang** [comment]
Please ignore that.

**Comment by spongezhang** [comment]
Take a look at the benchmark. https://github.com/EGO4D/social-interactions/blob/lam/dataset/data_loader.py#L126 It seems to me all social_segments_looking "is_at_me" should be labelled as True. Not looking at me is not labelled.

**Comment by ebyrne** [comment]
Yes, that's correct.  We have an update coming out shortly, but you can essentially treat all looking at me annotations as True for practical purposes.

**Comment by spongezhang** [comment]
Awesome. Thanks for confirming that!
