### ISSUE TITLE
How to read annotations of egocentric gaze?

### ISSUE THREAD

**Issue by LAIBOLIN** [facebookresearch/Ego4d#54]
I want to do some research regarding egocentric attention prediction. It should be under social benchmark, but I can't find it in av_val.json. I only found tracking paths of participants and whether they are looking at the wearer. How can I read annotations of the wearer's gaze?

**Comment by ebyrne** [comment]
Hi Bolin, Gaze will be available shortly.   I'll leave this issue open until it is and we'll notify here.

**Comment by miguelmartin75** [comment]
Gaze data is available now. I've added docs in https://github.com/EGO4D/docs/pull/6. Download with `--datasets gaze`

Please let us know how usage of the gaze data goes! Feel free to re-open this issue if you have any further issues with it.
