### ISSUE TITLE
3D data for Ego4D

### ISSUE THREAD

**Issue by mbanani** [facebookresearch/Ego4d#61]
Thanks for the data release. The paper detailed 3D mesh for 491 hours of the dataset, but I was unable to find anything related to meshes or which videos came with meshes in the release docs. Will this be released? Thanks! 

Update: there are `3d` and `3d_scans` options for the dataset that provide a set of json files with annotations and dataset splits (3d) and a set of 16 tar-files that contain 3D mesh and point cloud information for 16 scenes. Is this the full dataset or are files still being added to this? Thanks again for all your work!

**Comment by devanshk** [comment]
Hey @mbanani, thanks for reaching out! The 3D data downloaded via the cli (`3d_scans` and `3d_scan_keypoints`) is the full dataset, we're not planning to add more right now. This includes the 15 3d_scan .tars and the 7 3d_scan_keypoints .tgzs Please let us know if any of the data is confusing or missing.

We **are** working on a doc page for the 3D data and will link it here when that's up! Keeping this task open until then!

**Comment by iranroman** [comment]
Hello, can you please link to the doc page to the 3D data? I cannot find it on the website. Thanks!
