### ISSUE TITLE
benchmark flag for " Short-term object interaction anticipation "

### ISSUE THREAD

**Issue by luohwu** [facebookresearch/Ego4d#65]
Dear EGO4D team,
 
Thank you for your great work.

Does the '--benchmark' flags only support "EM, FHO, AV" so far? 
I would like to download the parts for the benchmark " Short-term object interaction anticipation ". I tried "--benchmark sta", it just showed 0 objects are available. Am I using wrong option, or the benchmark has not been released yet

**Comment by luohwu** [comment]
I have checked the code, the it says "The benchmarks to download dataset subsets of: 'EM', 'FHO', 'AV'". 
'STA' is not among them

**Comment by devanshk** [comment]
STA is part of the FHO benchmark, we don't splice the benchmarks by sta/lta/scod yet.

You can download the annotations with
```
python -m ego4d.cli.cli --output_directory=<OUTPUT_DIR> --datasets annotations
```
and you'll find the files 'fho_sta_train.json' and 'fho_sta_val.json' in the annotations/ folder.

the benchmark models with
```
python -m ego4d.cli.cli --output_directory=<OUTPUT_DIR> --datasets sta_models
```

and the clips with
```
python -m ego4d.cli.cli --datasets clips --output_directory="~/ego4d_data" --benchmarks FHO
```

There's more info on the structure of these annotations in the [Forecasting docs](https://ego4d-data.org/docs/benchmarks/forecasting/).

Good catch on the benchmark flags, seems we missed documenting that. I'll add all the options to the cli README.

**Comment by luohwu** [comment]
@devanshk
