### ISSUE TITLE
[Documentation] Broken link while referring to metadata and annotations overview 

### ISSUE THREAD

**Issue by pranay-ar** [facebookresearch/Ego4d#66]
Thank you for the great work. I was reading about the dataset and while trying to find the metadata details, I discovered that the link directing to the overview of annotations and metadata does not exist yet. I did not find the repository for Ego-4D docs to report it there (sorry if I missed it). Here's the link that I am talking about (did not find a better way to represent it)

![broken_link](https://user-images.githubusercontent.com/47575027/156230157-46348a05-9559-438a-bb1d-c7606e02967f.jpg)

Could you please update it to the correct link so that is easier to find it in the documentation. ( I suppose it is [this](https://ego4d-data.org/docs/data/metadata/) and [this](https://ego4d-data.org/docs/data/annotations/)?). Thank you.

**Comment by devanshk** [comment]
Thanks for catching this @pranay-ar! Fixed in https://github.com/EGO4D/EGO4D.github.io/pull/16!
