### ISSUE TITLE
Cannot download "fut_loc" etc.

### ISSUE THREAD

**Issue by TengdaHan** [facebookresearch/Ego4d#68]
Hi Ego4D team,

I am tring to download everything as this table shows: https://github.com/facebookresearch/Ego4d/blob/main/ego4d/cli/README.md#datasets 

However, right now I cannot download `fut_loc`, `lta_models` and `vq2s_models`. The rest of the dataset tags all work fine.

The error message I received (for all three cases) is 
```
botocore.exceptions.ClientError: An error occurred (403) when calling the HeadObject operation: Forbidden
```

Will these datasets be released soon, or it's the problem from my side?

Thanks!

**Comment by ebyrne** [comment]
Please try again.  That was an error on our side, and vq2s_models was mispelled - please use vq2d_models.  (Updated in the docs, will hit the repo shortly.)

Thanks!

**Comment by sinaazar** [comment]
Hi

I tries vq2d_models and I can't get the models.
This is what I get:
It seems vq2d_models.zip is missing.
```
Boto 403 Exception For exists: d0733076-d3e8-4f5b-bafc-abc689301693 | vq2d_models.zip
Missing s3 object (ignored for download): d0733076-d3e8-4f5b-bafc-abc689301693 | vq2d_models.zip
100%|███████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  7.06file/s]
Filtered 1/1 existing videos for download.
ERROR:root:1/1 missing S3 downloads will be ignored
The latest versions of all requested videos already exist in the output directories under:
```

Thanks

**Comment by sinaazar** [comment]
Thanks it is working now

**Comment by ZhiwenShao** [comment]
Could you download the fut_loc? I meet the same issue as you.
