### ISSUE TITLE
Benchmarks specified but ignored without a benchmarks field in manifest.

### ISSUE THREAD

**Issue by kylemin** [facebookresearch/Ego4d#69]
I got the following warning message: Benchmarks specified but ignored without a benchmarks field in manifest.
I used the following command line:
```
python -m ego4d.cli.cli --output_directory="/datasets/ego4d" --datasets clips annotations viz slowfast8x8_r101_k400 av_models --metadata --benchmarks AV -y
```

**Comment by ebyrne** [comment]
That's just a result of benchmarks not being relevant for some of the datasets specified.  No issue there.  We can clean up the error message.  

Thanks Kyle

**Comment by kylemin** [comment]
Thanks!
