### ISSUE TITLE
CLI script is attempting to download all files instead of download only non exist files in the file system.

### ISSUE THREAD

**Issue by ramkumarkoppu** [facebookresearch/Ego4d#75]
If download is interrupted for any reason (example computer reboot due to OS updates), next run of CLI script is attempting to download all files instead of download only non exist files in the file system. It's not efficient way of download for this size of data.

**Comment by ebyrne** [comment]
Yes, that's a known limitation and we'll make an improvement for it in the future.  In the meantime, please let the download complete and the entries will be updated appropriately.  (You can download the larger datasets individually if you're concerned about net download time without an interruption.)
