### ISSUE TITLE
How to download gaze annotation

### ISSUE THREAD

**Issue by LAIBOLIN** [facebookresearch/Ego4d#79]
I downloaded gaze data using command `python3 -m ego4d.cli.cli --output_directory=/Data/Ego4D --datasets gaze`, but I still have two issues about gaze data.

(1) I don't find annotations in downloaded data. How can I get them?

(2) I tried to play these videos, but there's always an error from player. I can play videos of other benchmarks. Could you check whether these videos regarding gaze are damaged?

**Comment by ebyrne** [comment]
Could you give us more detail what videos you're trying to play?  There aren't any videos in the gaze dataset specifically.  Likewise there aren't any annotations.  Please see the documentation at: https://ego4d-data.org/docs/data/gaze/

Let us know if you have further questions from there.

**Comment by LAIBOLIN** [comment]
I'm trying to download videos with gaze annotations. From your link, I should download them using the command `python3 -m ego4d.cli.cli --output_directory=/Data/Ego4D --datasets gaze`. I downloaded all gaze data, but I failed to play them. There's an error 'The file isn’t compatible with QuickTime Player'. I attached one video here.

As for the annotation, the official document shows some samples of gaze annotations in csv, so they should be available. I just want to know how to get them.

I can't reopen this issue. Could you help me to do this?
