### ISSUE TITLE
IT is very difficult for Chinese researchers download ego4d-data

### ISSUE THREAD

**Issue by lihuinian** [facebookresearch/Ego4d#86]
command line: python -m ego4d.cli.cli --yes --datasets clips --benchmarks FHO --metadata --output_directory ~/ego4d_data/
when I run this command,I met this problem(showing in figures) 
![image](https://user-images.githubusercontent.com/36408444/161382696-fbdad521-a1d9-4b1a-9c53-681d7a1727d0.png)
![image](https://user-images.githubusercontent.com/36408444/161382808-ea027a63-0202-429f-b965-ba29f1a04c04.png)
![image](https://user-images.githubusercontent.com/36408444/161382829-1b937f34-7a53-4c47-a3f3-1122e5fb664a.png)

**Comment by NNNNAI** [comment]
I meet the same problem, it is really hard to download this dataset in china. Did you find a way to solve it ? @lihuinian

**Comment by LostXine** [comment]
Try `proxychain` if you can find a good proxy.

**Comment by liuchenxjtu** [comment]
> I meet the same problem, it is really hard to download this dataset in china. Did you find a way to solve it ? @lihuinian

any solution about this? @NNNNAI

**Comment by hjl1012** [comment]
> I meet the same problem, it is really hard to download this dataset in china. Did you find a way to solve it ? @lihuinian

Me too! Did you find any solution? @NNNNAI @lihuinian

**Comment by devanshk** [comment]
Hey folks, thanks for your patience. Ego4D should now be fully accessible from China without VPN. We've moved some files around, made updates to the CLI to make downloads more reliable, and tested the fixes with a few researchers in China.

Please make sure you're on the latest version of the CLI by running ```pip install --upgrade ego4d``` before downloading, and feel free to comment or open new issues if you have any problems!

**Comment by hjl1012** [comment]
您好，已收到您的邮件，我会尽快处理。（I have received your e-mail. Thank you!）

**Comment by jasonrayshd** [comment]
@devanshk Hi, I try to download Ego4D dataset with latest version CLI but the download process is quite unstable. Frequently (4 out of 5), I got error below and the download will be interrupted
```
...  

ConnectionResetError: [Errno 104] Connection reset by peer   
During handling of the above exception, another exception occurred:   
...  
botocore.exceptions.ConnectionClosedError: Connection was closed before we received a valid response from endpoint URL: "https://ego4d-iiith.s3.ap-south-1.amazonaws.com/"
```

**Comment by MiraclesinWang** [comment]
> 

I meet the same problem. It seems if I enable VPN, I cannot pass SSL verification. If I disable VPN, then I met the "botocore.exceptions.ConnectionClosedError: Connection was closed before we received a valid response from endpoint URL: 'https://ego4d-iiith.s3.ap-south-1.amazonaws.com/'". 
Chinese researchers are so tough.

**Comment by hjl1012** [comment]
您好，已收到您的邮件，我会尽快处理。（I have received your e-mail. Thank you!）

**Comment by Zoe-Ziyi** [comment]
same problem with @MiraclesinWang, any solution please?

**Comment by MiraclesinWang** [comment]
Well, after several days' debugging, I think I have found the problem. 
Servers in the region 'ap-south-1' seem to block China's IPs. That's why when you try to download any file on those servers, you will receive 
```
botocore.exceptions.ConnectionClosedError: Connection was closed before we received a valid response from endpoint URL: "https://ego4d-iiith.s3.ap-south-1.amazonaws.com/"
```
The solution is to use VPN, clash-linux as an example, to modify your IP and pass the verification of servers in the region 'ap-south-1', then you can download files.
I have succeeded, may this solution works for others. 
Finally, I have to agree with this post's title, 'It is very difficult for Chinese researchers'.
BTW, if possible, can you help move the files on servers in the region 'ap-south-1' to other regions' servers? If so, Chinese researchers will face fewer problems. Thanks a lot. @devanshk

**Comment by Zoe-Ziyi** [comment]
Thanks for your reply. I have installed the clash-linux as you recommended. Could you tell me how to modify the IP to pass the verification? Many thanks anyway. @MiraclesinWang

**Comment by MiraclesinWang** [comment]
> Thanks for your reply. I have installed the clash-linux as you recommended. Could you tell me how to modify the IP to pass the verification? Many thanks anyway. @MiraclesinWang

Actually, clash-linux is like a plane. You also need a ticket before you can fly anywhere. You need to buy VPN service in China, then you can ask the service provider for config.yaml (your ticket). After adding the config.yaml to your clash-linux setting, you can use the VPN as your proxy, with which you can confuse the servers in the region 'ap-south-1' about your ip.

**Comment by cyfedu1024** [comment]
Hi, bro, i use the shadowsocks in Clash-linux, but i have to face a new issues: limited network flow：100G per month. Do you meet this problem? how to solve it? Thanks a lot!!!(The dataset almost 7 TB, limited flow cannot download completely.)

**Comment by cyfedu1024** [comment]
> > 
> 
> I meet the same problem. It seems if I enable proxy, I cannot pass SSL verification. If I disable proxy, then I meet the "botocore.exceptions.ConnectionClosedError: Connection was closed before we received a valid response from endpoint URL: 'https://ego4d-iiith.s3.ap-south-1.amazonaws.com/'". Chinese researchers are so tough. Have you found any ways to tackle this problem? If so, can you do me a favour by giving me some suggestions? Thanks!

方便加您微信吗？想咨询一下解决方式，我目前在国内，也遇到这个问题，开启VPN有流量限制，无法完整下载某些任务的数据集，我的联系方式：微信：CYFNUCBJTUDUT
