### ISSUE TITLE
Mapping between narrations and FHO annotations

### ISSUE THREAD

**Issue by dariofugale95** [facebookresearch/Ego4d#87]
I'm trying to get a subset of FHO benchmark data whose observations also have associated narrations.

In particular, for each triplet of critical frames in FHO-SCOD, I would like to be able to get the corresponding narration.

Is there an explicit mapping between FHO annotations and narrations that would allow me to achieve my goal? Or, if it does not exist, is it possible to derive this mapping through some procedure?

**Comment by miguelmartin75** [comment]
Sorry for the delay on this issue. We will be providing another annotation JSON with this mapping. Right now it is non-trivial to map back to the narrations.

**Comment by miguelmartin75** [comment]
This is now possible with V2. Please refer to: https://ego4d-data.org/docs/tutorials/FHO_Overview/
