### ISSUE TITLE
Extension of Gaze information

### ISSUE THREAD

**Issue by Evm7** [facebookresearch/Ego4d#91]
First of all, congratulations for the Dataset provided.

Regarding the Gaze data provided by Ego4D, only around 31 videos contain this type of modality. I am interested in the usage of Gaze data for the Forecasting Human-Object Interaction Challenge, but none of the videos of these challenge contain this data.

Therefore, is all the gaze data for the EGO4D videos already been provided, or it is planned to be released more data for a bigger subset of videos and chllenges?

(Videos from EGO4D Videos with Gaze: 31/9645 --> Only 0.321% of videos contain gaze)

**Comment by miguelmartin75** [comment]
There will be more data collected in the future. I cannot say whether there will be more gaze data collected. Likely there will be but there is no guarantee.
