### ISSUE TITLE
how can I get the traning dataset for state change object detection.

### ISSUE THREAD

**Issue by NNNNAI** [facebookresearch/Ego4d#94]
Thanks for sharing your work. I notice that the training data for [state change object detection](https://github.com/EGO4D/hands-and-objects/tree/main/state-change-object-detection-baselines) are PRE + PNR + POST image pairs.  However, when I download the data by using command line as shown below, all I got are videos not images. How can I get those images? Do I need to process the raw video to got the image pairs?
```
python -m ego4d.cli.cli --output_directory=/home/naliu/Data/Datasets_tmp/ego4d/fho --dataset full_scale --benchmark fho
```

**Comment by miguelmartin75** [comment]
This is answered on https://github.com/EGO4D/hands-and-objects/issues/6
