### ISSUE TITLE
Annotation file for object state change classification missing

### ISSUE THREAD

**Issue by Chuhanxx** [facebookresearch/Ego4d#95]
Dear Ego4D team,

Thank you for the excellent dataset.
According to https://github.com/EGO4D/hands-and-objects, there supposed to be three annotation files for the hand object interaction task. but 'fho_oscc-pnr_<set>.json' for Object state change classification seems to be missing in the CLI.

**Comment by ebyrne** [comment]
fho_oscc-pnr_*.json is correct and used for both PNR and Object State Change.  Apologies on the delay here!
