### ISSUE TITLE
Cannot download dataset

### ISSUE THREAD

**Issue by HarshayuGirase** [facebookresearch/Ego4d#96]
Hi,

Thanks for the dataset! I'm currently facing this issue and I'm not sure what may be causing it:
<img width="1257" alt="Screen Shot 2022-04-19 at 11 01 16 PM" src="https://user-images.githubusercontent.com/10692739/164161030-241828f6-6c32-42fa-920d-5b6c89ef61a5.png">

**Comment by miguelmartin75** [comment]
Please use python3.8 and above. Let us know how it goes.
