### ISSUE TITLE
Annotation file details for AV Diarization and Social Interactions

### ISSUE THREAD

**Issue by sammy-su** [facebookresearch/Ego4d#98]
Hi,

I wonder if it's possible to provide an explanation for each field in the annotation files? Some particular problems I encountered while reading the annotation file includes:

1. What's the relationship between clip_uid, source_clip_uid, and video_uid? It seems like that clip_uid refers to canonical clip while video_uid refers to canonical video, but what about source_clip_uid? Similarly, what's the relationship between (video_start_sec, clip_start_sec), (frame, video_frame, clip_frame, start_frame), etc.?

2. Following the previous question, does this means that canonical videos are a concatenation of multiple canonical clip, and if so, how to determine which clips are concatenated together and their boundaries in canonical videos?

3. What does the following filed means?

- videos/clips/valid
- videos/clips/persons/tracking_paths/unmapped_frames
- videos/clips/persons/tracking_paths/suspect
- videos/clips/social_segments_talking/target

4. Regarding the person_id, it seems like the ids are zero-based where 0 indicating the camera wearer. However, the benchmark challenge description indicates that the camera wearer should have id -1, and -1 also appears in social_segments. Is it possible to clarify the meaning of person_id?

**Comment by ebyrne** [comment]
1.  We'll get those updated on the docs.  source_clip_uid is effectively internal only - you won't need that.  video_ and clip_ fields respectively refer to canonical videos and clips as you mention.
2. The canonical videos are the primary videos.  Clips were constructed for various annotation tasks and are not necessarily (almost certainly) a full representation of the video, though particularly for narrations the coverage would be high.  [Read more on the docs](https://ego4d-data.org/docs/data/videos/)
3. valid is an indication internal checks all passed.  unmapped_frames and suspect treat as internal. target is the target that the person is interacting with.  (We'll update the [annotations](https://ego4d-data.org/docs/data/annotations-schemas/) for that as well.
4. Agreed, that's a little confusing.  0 there is indeed the camera wearer.  -1 is correct in the social segments and indicates there isn't a target, which is effectively the same thing here.  (Please reach out to the [specific repo](https://github.com/EGO4D/social-interactions/issues) for further questions there, or the [forum](https://discuss.ego4d-data.org/).  Apologies on the delay here!
