### ISSUE TITLE
Annotation details for long-term action anticipation

### ISSUE THREAD

**Issue by sammy-su** [facebookresearch/Ego4d#99]
Hi,

I wonder if it's possible to provide an explanation for each field in the annotation files? Specifically, I wonder what's the relationship between clip_parent_start_sec, interval_start_sec, action_clip_start_sec, etc.

**Comment by ebyrne** [comment]
An excellent suggestion.  This is coming shortly and will be updated in the docs in the next few days.

**Comment by dmoltisanti** [comment]
Hello and thanks for your work!

I was looking for the same details, though for another challenge (object state challenge classification).

In particular, I was wondering how `clip_start_frame` and `parent_start_frame` differ in `fho_oscc-pnr_val.json` (and in all json files including clip/parent annotations).

Where can I find this information? 

Thanks in advance!
